### ISSUE TITLE
Long quotes can still cover text

### ISSUE THREAD

**Issue by kakol20** [ermiyaeskandary/Slither.io-bot#104]
http://img.prntscr.com/img?url=http://i.imgur.com/YnUsV1y.png

**Comment by ermiyaeskandary** [comment]
Make a new issue for the bot respawns and then turns off. For the current quote, its over the limit and its not important. We can't move it down any further or it will look weird.

**Comment by Seple** [comment]
Again problem

http://s32.postimg.org/612mn1a4l/Hud2.jpg

Better

http://s32.postimg.org/aiuq9tojp/HUD.jpg

**Comment by ermiyaeskandary** [comment]
Yeah - it would look weird if we move it even further down when there is no message. Maybe move the message around ?

**Comment by ChadSki** [comment]
Nicknames aren't supposed to be longer than 25 characters, I call hacks

**Comment by Seple** [comment]
hmmm
maybe a new place suitable for menu 
look ------>>> http://s32.postimg.org/4u4n85zid/menu.jpg

**Comment by chancity** [comment]
We need a menu of menus and a hot key to show the main menu

**Comment by chancity** [comment]
Maybe a menu bar at the top of the screen that always shows

**Comment by Seple** [comment]
> We need a menu of menus and a hot key to show the main menu

YES

**Comment by kakol20** [comment]
@ChadSki I think it was a quote, the person's username was actually starlord.

Who knows, I never had the longest length

**Comment by ChadSki** [comment]
There's no way to communicate other than usernames as far as I know. Slither.io might only be doing client side length evaluation and, starlord hacked around that.

**Comment by ChadSki** [comment]
Oh wait, it does look like a quote. Does the site prompt for a quote when you're the longest?

**Comment by Drflash55** [comment]
@ChadSki Yes... If your the largest snake in the game, it will ask you to input a message for everyone to see.

**Comment by chancity** [comment]
Look for victory or victorymessage in the source code

**Comment by ermiyaeskandary** [comment]
There is a clientside packet sent...

**Comment by ermiyaeskandary** [comment]
OFFTRACK ALERT
Which sends the longest snake message... But I'm sure it won't be easy to hack it...

**Comment by kakol20** [comment]
@chancity Something like this? view-source:http://slither.io/ (Go to slither.io and press Ctrl + U )

Line 189

I think this is the main code for the game:
http://slither.io/s/game20fjk.js _You can make it readable using this site: http://www.danstools.com/javascript-beautify/_

**Comment by chancity** [comment]
```
// Remove social
window.social.remove();
//Remove victory message
window.vcm.remove();
```

![image](https://cloud.githubusercontent.com/assets/8220501/15130169/4d86dd32-15fb-11e6-88e8-91a404ec7273.png)

**Comment by kakol20** [comment]
The above should work

**Comment by ChadSki** [comment]
What if we just append our menu items to wherever the victory message is placed?

That way it always lines up appropriately and we don't need to adjust absolute coordinates.

**Comment by ermiyaeskandary** [comment]
It's been removed in the latest PR merge ...

**Comment by ermiyaeskandary** [comment]
Fixed ... Victory messaged removed...
