### ISSUE TITLE
Auto mobile rendering bug

### ISSUE THREAD

**Issue by kakol20** [ermiyaeskandary/Slither.io-bot#106]
It seems that the enable/disabled text for mobile rendering is reversed. It says its disabled but it actually is enabled.

**Comment by Seple** [comment]
and jumping fps?

**Comment by ermiyaeskandary** [comment]
I was thinking of removing it but didn't get the thumbs up from @Evanito as he was the one who suggested this feature.

**Comment by ermiyaeskandary** [comment]
I'm removing as it is not needed but we might be able to check FPS later and decrease the bot interval..

**Comment by ermiyaeskandary** [comment]
Lower FPS confirmed... Not really useful ATM and has more cons than pros ... Removing
