### ISSUE TITLE
Confusion between coordinate systems - Documentation

### ISSUE THREAD

**Issue by ChadSki** [ermiyaeskandary/Slither.io-bot#107]
- Canvas pixels
- Canvas coordinates
- Coordinates relative to snake
- Window coordinates
- Whether "scale" has already been applied or not

We're not keeping clear track of these things, which is the root cause of [issue #100](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/100) and probably other things.

Solution = documentation and annotations?

**Comment by ermiyaeskandary** [comment]
I totally agree. @FliiFe should have the most knowledge about the converter functions as he was the one who went through the code and made it. **We do need documentation :+1:**

**Comment by ermiyaeskandary** [comment]
We all are working on documentation.....

**Comment by tjbcg** [comment]
@ErmiyaEskandary Will work on doc tonight. I have been away for quite some time now, but I think I can still do it. I didn't know conversion wasn't clear :-D

**Comment by ChadSki** [comment]
[Pull #143](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/143) fixes a big piece of this problem by always using _map coordinates_ for bot math.

**Comment by ermiyaeskandary** [comment]
@FliiFe is also going to work on doc for the conversion methods...

**Comment by ermiyaeskandary** [comment]
continue conversation in #161 from now on please...
