### ISSUE TITLE
Avoid enemies when boosting for dead snakes

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#116]
Whether the line of the road to eat - may have a condition - not touch the other snake? (do not go by snake)

Please fix this
https://files.gitter.im/ErmiyaEskandary/Slither.io-bot/JKEL/hmmmm.png (Only work "circle")

**Comment by Drflash55** [comment]
This is confirmed... The bot goes after food that is behind other snakes and it won't give up until it can get there...

**Comment by ermiyaeskandary** [comment]
Doesn't apply anymore - doesn't boost currently

**Comment by Seple** [comment]
the problem occurs all the time
