### ISSUE TITLE
Bot gets stuck circling food

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#12]
Bot gets stuck trying to eat a single piece.

Potential solutions:
- Ignore food closer than n units to the left or right (Do we have currentBotAngle detection?) since these food will most likely be within our turning radius.
- Solve issue #13 
- If we solve #23 then the bot would be very unlikely to get stuck on one.

**Comment by tjbcg** [comment]
> Do we have currentBotAngle detection?

We don't. The bot is currently not working with angles, and that is something we should implement...

**Comment by tjbcg** [comment]
Needs #22

**Comment by ghost** [comment]
maybe it checks if a food is close to it and if it hasn't been eaten for a certain amount of times it chooses a new food? @FliiFe

**Comment by tjbcg** [comment]
@Classicanon That is more of a workaround than a real fix. Could temporarily works, but @ErmiyaEskandary and I are working on angles.

**Comment by ghost** [comment]
@FliiFe yea but at least it would work until you and @ErmiyaEskandary get angles working i really should learn JavaScript so i can at least help with things

**Comment by tjbcg** [comment]
@Classicanon Help on logic is still really helpful. For example, I'm almost sure no one in the team thought of that.

**Comment by tjbcg** [comment]
So, assuming we have angles working. Should we avoid food on the sides, or use only the food in front of the bot ? Please see [this](http://imgur.com/a/ZcXQP) for visual representation of my question.

**Comment by ermiyaeskandary** [comment]
I would say go only after food in front as that would help with clustering food and with eating food in a straight line without zigzagging constantly from food to food e.g when a snake dies

**Comment by ermiyaeskandary** [comment]
Who agrees ?

**Comment by K00sKlust** [comment]
I do. :)

**Comment by dracco1993** [comment]
@FliiFe I think it needs to be a combination of angle and distance.
For example:
- Close on the side: Bad
- Close in front: Good
- Far on side: Okay
- Far in front: Okay

**Comment by tjbcg** [comment]
@dracco1993 Note taken.

**Comment by ermiyaeskandary** [comment]
Please read #22. Angles will not be implemented anymore. We need another way to fix this. 
Ideas ?

**Comment by Seple** [comment]
> @Classicanon maybe it checks if a food is close to it and if it hasn't been eaten for a certain amount of times it chooses a new food?

or sideways after (for example) 3 circles?

**Comment by tjbcg** [comment]
@Seple These are workarounds. I am working on this.

**Comment by Seple** [comment]
@FliiFe  Thank you! Your band is magnificent!

**Comment by ermiyaeskandary** [comment]
@Seple band ?

**Comment by ChadSki** [comment]
@FliiFe I like your visualization, but I had a thought while looking at it.

![visualization of straight and rounded angles](http://i.imgur.com/7HFSg2d.png)

Really the snake is not bounded by straight angles, but continuously curved angles -- whatever is the tightest possible turn the snake can make at its present size.

**Comment by Seple** [comment]
> Thank you! Your band is magnificent!

*band = group dewelopers

**Comment by tjbcg** [comment]
@ChadSki That's a great idea !
I will first implement the angle version, as it is almost finished.

Would that work ? Snake can take food behind, on the sides, etc, without getting stuck circling food
![Danger zones](https://cloud.githubusercontent.com/assets/8740385/15068964/f9e8ecec-137a-11e6-8b87-0cacce1c76b0.png)

**Comment by Drflash55** [comment]
Wow. Look how far we came...

We were finally able to fix one of the bot's very first bugs...
Pat on the back to those who contributed.

**Comment by ermiyaeskandary** [comment]
^
