### ISSUE TITLE
Your codes stolen

### ISSUE THREAD

**Issue by Slitherio-Org** [ermiyaeskandary/Slither.io-bot#121]
https://chrome.google.com/webstore/detail/slitherio-bot-mod-bot-hac/akelenihbmammmenhmijhngpjdbmpiib

**Comment by tjorim** [comment]
Thanks for letting us know. However, we were already informed of this.

I think there is not much we can do bacause of the MIT-license.

**Comment by ermiyaeskandary** [comment]
I'm thinking of changing...

**Comment by Fredyy90** [comment]
Isn't this the slithere.com guy?
So now we know what he means by "sharing on his website" :D

He edited his first post, but he mentioned "slithere.com" in his post before the editing.

https://github.com/ErmiyaEskandary/Slither.io-bot/issues/30

**Comment by ermiyaeskandary** [comment]
Ah - yep!

**Comment by ermiyaeskandary** [comment]
License has been changed - 

> For example, if you distribute copies of such a program, whether gratis or for a fee, you must pass on to the recipients the same freedoms that you received. You must make sure that they, too, receive or can get the source code. And you must show them these terms so they know their rights."

Therefore, they need to give credit, include source code and include the GNU General Public License. I have commented on their website and the extension they have released.

**Comment by Seple** [comment]
License does not stop thief. 
Better to add advertisement in the menu

**Comment by Seple** [comment]
License does not stop thief. 
Better to add advertisement (www.your_site) in the menu

**Comment by Slitherio-Org** [comment]
Also on your tutorial list.
https://i.imgur.com/5Om63dD.png

ErmiyaEskandary can you add me to Skype please? Skype: slitherio.org

**Comment by ermiyaeskandary** [comment]
@Slitherio-Org Yeah - I personally put the video there. We are not against advertisement - we are against people who do "theft"

**Comment by Slitherio-Org** [comment]
Nice think, they also stolen our all codes and content, we report to google from here
https://support.google.com/legal/contact/lr_dmca?&product=chromewebstoreextensionsgallery

**Comment by ermiyaeskandary** [comment]
@Slitherio-Org Currently waiting for their response...

**Comment by Slitherio-Org** [comment]
Good luck for you :) And if you have time please add to me skype, we have some project, also want to use your bot as well.

**Comment by Slitherio-Org** [comment]
Sorry i forgot the share this :)
https://greasyfork.org/en/scripts/19378-slither-io-bot-0-6-8-slithere-com/code

They say thanks to you :) But you are lucky man, they stolen everything only thanks to you.
https://greasyfork.org/en/scripts/by-site/slither.io

**Comment by ermiyaeskandary** [comment]
We have no problem with the source code - the extension being closed source is the part we are dealing. To contact me or anyone else in the team, join our Gitter team - link in README.

**Comment by Drflash55** [comment]
Oh hey, @Slitherio-Org. Nice to have you here...  This is off-topic, but you were the first site to publish a bot that could play Slither.io. Congrats on that...

**Comment by Slitherio-Org** [comment]
Thanks @Drflash55

**Comment by tjorim** [comment]
Looks like slithere took both their/his app/extensions down (or Google did :grinning: )
https://chrome.google.com/webstore/detail/slitherio-mods-hacks-chea/elmnkcenofoinaoklnbhhkelfplbfjmp
https://chrome.google.com/webstore/detail/slitherio-bot-mod-bot-hac/akelenihbmammmenhmijhngpjdbmpiib

**Comment by ermiyaeskandary** [comment]
Confirmed yesterday - I'm in touch with author :) expect updates...

**Comment by ermiyaeskandary** [comment]
Author has agreed to sharing link to this repo , giving credit and sharing license. Extension was taken down by Google lol - supposed to be back up soon :)
