### ISSUE TITLE
Use next food to predict angle it should eat current food at

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#13]
Essentially, add a predictor that makes the bot eat its current target at an angle that will make it easy to eat the next one.

Since snakes can't turn on a dime, this is needed to eat long chains of food without extreme wiggles.

**Comment by ermiyaeskandary** [comment]
#22

**Comment by ermiyaeskandary** [comment]
Please read #22. Angles will not be implemented. We need another way to implement this. 
Ideas ?

**Comment by ermiyaeskandary** [comment]
Done with the latest commits...
