### ISSUE TITLE
Interactive tutorial

### ISSUE THREAD

**Issue by jLynx** [ermiyaeskandary/Slither.io-bot#132]
Hey guys, not sure if oyu know who I am, but I made the aga.io interatcive website bot.jlynx.net
Anyway, just wanted to let you know I have now made one for you bot: http://slither.jlynx.net/

I have given you credit and everything links back to your github.
Would you be able to add the link to the read me to help users who are getting confused to install the bot?

**Comment by Drflash55** [comment]
Thanks for making the interactive website for our bot...
@ErmiyaEskandary please, add this to our readme for those who don't want to add the script manually... or those who have no idea on how to.

**Comment by jLynx** [comment]
I have done this, you just need to accept the change 
https://github.com/DarkN3ss61/Slither.io-bot/commit/4e0ae50129b318146b7793bc1f99fad389eef06f

**Comment by Evanito** [comment]
@DarkN3ss61 Appreciated, but either make a PR for this change or ask someone to add it manually. (I would be happy to)

**Comment by jLynx** [comment]
Go ahead and add it manually :)

## Interactive tutorial

 http://slither.jlynx.net/

**Comment by Drflash55** [comment]
@DarkN3ss61 Make a PR to update the README.MD, collaborators don't have the powers to edit the master branch, so we need checks to go through in order to get it to work...

**Comment by jLynx** [comment]
@Drflash55 Created a pull requet https://github.com/ErmiyaEskandary/Slither.io-bot/pull/133
