### ISSUE TITLE
Prioritize big food

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#14]
Bot should prioritize big food since it is better in every way. 
- Maybe half its distance when calculating nearest food to give bot a preference?

But first, we need to be able to discern big food from the rest.

**Comment by ermiyaeskandary** [comment]
> Maybe half its distance when calculating nearest food to give bot a preference?

What's the point of halving the distance ? That would give a preference to closer food which it already does. What we want is a way to distinguish big food from small food. After that, it's like drinking water - simple and easy.

**Comment by K00sKlust** [comment]
Maybe divide the distance by the size?

**Comment by ermiyaeskandary** [comment]
> What we want is a way to distinguish big food from small food.

**Comment by ermiyaeskandary** [comment]
How would we find the size ? That's what we are after - the rest is _super easy_

**Comment by ermiyaeskandary** [comment]
I'll start working on this.

**Comment by K00sKlust** [comment]
I think its the variable .sz
`window.getSortedFood()[0].sz`

**Comment by tjbcg** [comment]
> > Maybe half its distance when calculating nearest food to give bot a preference?
> 
> What's the point of halving the distance ? That would give a preference to closer food which it already does. What we want is a way to distinguish big food from small food. After that, it's like drinking water - simple and easy.

The idea seems pretty good to me. If you halve only big food's distance, then it will be prioritized.

**Comment by ermiyaeskandary** [comment]
Misunderstood. After this :

> we need to be able to discern big food from the rest.

we can implement this. Big food is always better in every way and is a major step in improving the food hunt algorithm.

**Comment by ermiyaeskandary** [comment]
Implemented and tested. Big food prioritized over smaller food - great step forward !
