### ISSUE TITLE
Randomly going different places

### ISSUE THREAD

**Issue by kakol20** [ermiyaeskandary/Slither.io-bot#140]
Since the update, it has been going to different places and/or not focused on one place. You could tell because the green line and red dot is not on the screen and they keep going to different places. Wasn't a problem before.

http://prntscr.com/b39n31

**Comment by ermiyaeskandary** [comment]
After what commit is this confirmed ?

**Comment by ermiyaeskandary** [comment]
Either its the separate collision radiuses commit or the minor acceleration fixes. @kmatheussen ?

**Comment by kmatheussen** [comment]
Seems like the body radius (blue circle) has got the completely wrong value. It happens with me sometimes, I don't know why, but I thought it was just my local storage value that had become floating point, and that screwed up my system. But seems like it's not just me.

Anyway, the temporary solution is to press e and r to put back the blue circle.

**Comment by ermiyaeskandary** [comment]
Any idea why ? I can't and haven't tested the bot since the separate radius update.

**Comment by kmatheussen** [comment]
Perhaps some peculiarity with local storage, or loadPreference function.
It's now an int, but earlier it was a float. Perhaps local storage doesn't
understand
that. I really don't know.

**Comment by ermiyaeskandary** [comment]
Probably try removing the preference loading and saving to see if the issue arrives from the local storage ?

**Comment by ermiyaeskandary** [comment]
You wouldn't mind if I reverted your PR until you find out the fix ?

**Comment by kmatheussen** [comment]
I think I know the problem. It's interpreted as a string,
so we need to take convert it to number if it's string.

**Comment by ermiyaeskandary** [comment]
Can you join our Gitter ? Need your input :) Readme file

**Comment by kmatheussen** [comment]
I'll push a fix to the branch I'm working on, but
this is not a big problem. It should only be a problem
for those who checked out yesterday and today,
and still have data in local storage from yesterday.

On Thu, May 12, 2016 at 10:02 PM, Ermiya Eskandary <notifications@github.com

**Comment by kmatheussen** [comment]
Probably counterproductive to revert it. It will not help
those people who already got floats in local storage
plus that it will cause more people to get floats in local
storage since the number is a float in the reverted version.

**Comment by ermiyaeskandary** [comment]
Being discussed in Gitter chat ...
You can always add in PR's later ..

**Comment by ermiyaeskandary** [comment]
Is this still a bug with the latest PR merge ?
