### ISSUE TITLE
Body avoidance - size error

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#145]
Body avoidance radius random bigger size than specified, after death. One adjustment to the value with hotkeys brings it back to normal. Not only a visual debug error, but also detected at the size of the circle.

**Comment by ermiyaeskandary** [comment]
Is this still there after latest PR merge ?

**Comment by Salvationdk** [comment]
ill test

**Comment by Salvationdk** [comment]
fixed in 0.9.1
