### ISSUE TITLE
Defense mode is missing as of version 0.9

### ISSUE THREAD

**Issue by ChadSki** [ermiyaeskandary/Slither.io-bot#146]
It was omitted from @j-c-m's branch at the time we took the big merge.

**Comment by ChadSki** [comment]
Related to [issue #78 "New Defense Mode"](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/78), which has a number of thoughts and suggestions on how defense mode should work.

**Comment by ermiyaeskandary** [comment]
#147 - merged
