### ISSUE TITLE
Visual Debugging Issue on 32 bit browsers & Avoidance Bug

### ISSUE THREAD

**Issue by xpassionzxc** [ermiyaeskandary/Slither.io-bot#148]
There seems to be an issue with it. Its really bright T_T.

Also, I realized the avoidance of snakes is poorer after the update

**Comment by kakol20** [comment]
You're seeing something like this right?
![screenshot_29](https://cloud.githubusercontent.com/assets/14850826/15242606/0f39e884-18ef-11e6-9e11-a2449686ec49.png)

Like a cyan light?

**Comment by xpassionzxc** [comment]
Yeah something like that. But its white in colour. Like flashes.

**Comment by CJBoey** [comment]
And if you open console then you will see a lot of errors like this
`VM799162:140 Uncaught IndexSizeError: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-2.42439) is negative.`

**Comment by Drflash55** [comment]
There must be a problem with the calculations with the visual debugging... I haven't tested this out yet...

**Comment by ermiyaeskandary** [comment]
@Drflash55 Reminds me of the phantom bug in Apos's bot - :unamused: 
lol

**Comment by ermiyaeskandary** [comment]
> Also, I realized the avoidance of snakes is poorer after the update

This is due to the fact we have reverted backwards due to merging PR's and conflicts. 
Should see improvements soon...

**Comment by ghost** [comment]
ermiya wanna work together on slitherio bots/worms

**Comment by ermiyaeskandary** [comment]
@kurama129 Unfortunately and fortunately, I personally won't and I don't think others would support this idea.

**Comment by j-c-m** [comment]
I can't reproduce this bug.  The cyan circle is hard coded to a radius of 5, I have no idea how a negative number gets to arc()....

Any more information you can provide?

**Comment by ermiyaeskandary** [comment]
It doesn't cover the whole screen for me - just sometimes on snakes.

**Comment by ermiyaeskandary** [comment]
@chancity I thought you found out the solution ?!

**Comment by kakol20** [comment]
This bug could have some epilepsy issues. better fix it quick...

**Comment by j-c-m** [comment]
I can't reproduce it.  But I believe https://github.com/ErmiyaEskandary/Slither.io-bot/pull/158 fixes.

**Comment by j-c-m** [comment]
People with cyan bug please test bot: https://github.com/j-c-m/Slither.io-bot/raw/27f9fd74983d0cc5c7b9bceace83fd4854c340a2/bot.user.js

**Comment by kakol20** [comment]
Still happening :/

**Comment by kakol20** [comment]
![screenshot_32](https://cloud.githubusercontent.com/assets/14850826/15263438/ee5cd496-1961-11e6-9288-981661ddafe7.png)

**Comment by j-c-m** [comment]
Are you using the 32-bit or 64-bit version of chrome?

**Comment by kakol20** [comment]
32 bit

**Comment by j-c-m** [comment]
OK it is 32-bit vs 64-bit maths..... thank I think we can figure it out now.

**Comment by j-c-m** [comment]
try: https://github.com/j-c-m/Slither.io-bot/raw/dc31c5cfbb97be11207a9a93b6e32461d6b703f0/bot.user.js

**Comment by kakol20** [comment]
Same thing happening

**Comment by j-c-m** [comment]
https://github.com/j-c-m/Slither.io-bot/blob/5009284ac2e391954e6bcc20d80e799bc4ce5e59/bot.user.js

**Comment by ermiyaeskandary** [comment]
Still happening - I don't understand. It the same visual debugging code with a bit added. :confused:

**Comment by j-c-m** [comment]
It will work fine in 64-bit chrome.  The bug appears in 32-bit chrome. Will track it down.

**Comment by Seple** [comment]
64 bit have the same problem
Unfortunately, the bot is becoming Bug :(
The Best Version 8.2

**Comment by j-c-m** [comment]
64-bit chrome does not have the issue, check to make sure your Chrome is 64-bit, not just 64-bit OS.

**Comment by ermiyaeskandary** [comment]
What about other browsers ?

**Comment by Seple** [comment]
Chrome Ver: 50.0.2661.94 Win 64 bit
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36

**Comment by j-c-m** [comment]
https://github.com/ErmiyaEskandary/Slither.io-bot/pull/165

Please test: https://github.com/j-c-m/Slither.io-bot/raw/4dce136ba4d9bfbf29a4809c4a22c9b55dce2ee8/bot.user.js

Works for me!!!

**Comment by xpassionzxc** [comment]
yuppp jcm yours works
