### ISSUE TITLE
Add persistent settings on home screen

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#15]
Todo list:
- [x] Bot should have settings such as 
  - [x] To enable/disable console logging
  - [x] Preferred graphics quality
  - Which distance formula to use when we implement the new one
  - [x] Which name to use
  - [x] Whether or not to "autorespawn"
- [X] We need the bot to not instantly join the game the second the page loads.
- [x] Settings should be saved locally so they are persistent.
- [x]  Settings should be edited visually on the main screen or offer clear controls.
- [x] Saving code implemented
- [x] Loading code implemented

**Comment by ermiyaeskandary** [comment]
@Evanito We could use `localStorage`
