### ISSUE TITLE
.pullapprove.yml has some conflicts...

### ISSUE THREAD

**Issue by Drflash55** [ermiyaeskandary/Slither.io-bot#150]
~~Crap... sorry, gonna put a description here soon.~~

When checking out a PR, there's a problem with .pullapprove.yml... 

`{'required': 3, 'name': 'default', 'members': ['ChadSki', 'Drflash55', 'ErmiyaEskandary', 'Evanito', 'FliiFe', 'K00sKlust', 'j-c-m']}" is an invalid value for reviewers: 'j-c-m' is not a collaborator of this repo`

There's an invalid value for the reviewers code, and j-c-m can't be an approver, since he's not a collaborator of this repository... Please fix these problems so that it doesn't affect future PR's.

Collaborators, get more details here... https://pullapprove.com/ErmiyaEskandary/Slither.io-bot/settings/

**Comment by ermiyaeskandary** [comment]
The issue is that @j-c-m added himself as a reviewer...

**Comment by ermiyaeskandary** [comment]
Fixed...
