### ISSUE TITLE
to the people interested  in creating slither bots

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#152]
the aim of the project is to create feeder slither bots and create a bot service people who are interested can tell there skype id the requirements is have knowledge in js

**Comment by CJBoey** [comment]
It seems like an advertisement with 2 spelling mistakes in the title

**Comment by ghost** [comment]
its a typo

**Comment by ghost** [comment]
can you work with me

**Comment by ermiyaeskandary** [comment]
No we are not making feeder bots....
