### ISSUE TITLE
Monkeypatching the game's code

### ISSUE THREAD

**Issue by ChadSki** [ermiyaeskandary/Slither.io-bot#153]
Currently, the game's code runs as it always has. Our script's code runs on top and only moves the mouse to direct the snake.

Some enhancements, such as changing the way the game is rendered, can only be done by actually changing the game's underlying code.

We should have an approach for modifying the underlying game.

**Comment by ermiyaeskandary** [comment]
Ooooooohhhh.....
Hard thing to implement IMO at this moment in time...

**Comment by tjorim** [comment]
Yes indeed, like the zooming error #97

**Comment by tjbcg** [comment]
The issue we had is that we can't unload the game's script. And when we tried to modify the game's code, it was already loaded, so our version didn't work. (That was in the early days of the project :+1: ). That's why we have things like `oldOef` etc. We cannot modify their code, but we can add to their code and to their functions.

**Comment by tjorim** [comment]
@FliiFe What about this? It just updates the existing code without including all in our bot (so if the original changes, the fix would still apply unless the zooming itself has been altered by the game developer).
https://github.com/tjorim/Slither.io-bot/tree/zoomfix -> https://github.com/tjorim/Slither.io-bot/raw/zoomfix/bot.user.js

**Comment by ChadSki** [comment]
I like the string replace approach. If it can't find the string, the replace simply fails and the game does not break.

**Comment by tjorim** [comment]
Yes indeed, so it shouldn't affect the main game functions :D

**Comment by ChadSki** [comment]
Closing this issue because we know how to monkeypatch thanks to @tjorim :)
