### ISSUE TITLE
why blue things

### ISSUE THREAD

**Issue by eralpcicekdagi** [ermiyaeskandary/Slither.io-bot#159]
http://i.imgur.com/7856GzF.jpg

**Comment by ermiyaeskandary** [comment]
**Duplicate** of https://github.com/ErmiyaEskandary/Slither.io-bot/issues/148 : 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.
