### ISSUE TITLE
New workflow utilities

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#16]
I propose that we use https://waffle.io/ErmiyaEskandary/Slither.io-bot
based on the ideas of http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html

Of course, we will still use slacker for the main means of group communication, this helps organize and focus our open source group we have going here.

Thoughts on waffle.io?

**Comment by Drflash55** [comment]
This looks like a good place to organize stuff in...
