### ISSUE TITLE
[BUG] Blue things issue

### ISSUE THREAD

**Issue by eralpcicekdagi** [ermiyaeskandary/Slither.io-bot#160]
http://i.imgur.com/7856GzF.jpg
blue things the shortest description :)
google chrome
0.9.0 + 0.9.1
Tampermonkey
+i dont know why it cause
+i dont know any solition

**Comment by ermiyaeskandary** [comment]
**Duplicate** of https://github.com/ErmiyaEskandary/Slither.io-bot/issues/148 : 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.
