### ISSUE TITLE
[Version 0.9.2] Unable to toggle bot

### ISSUE THREAD

**Issue by xpassionzxc** [ermiyaeskandary/Slither.io-bot#169]
Once you try to disabled the bot and then reactivate it again. It is unable to be enabled again.

**Comment by dracco1993** [comment]
Confirmed.

**Comment by tjorim** [comment]
Please use the template for filing bugs.

> When making your report, be sure to mention:
>      - Title: Start title with `[Bug]` (Helps with labeling)
>      - Title: Short description of what the issue is. (Clearer the better.)
>      - Your browser. (Firefox, Google Chrome, etc.)
>      - What version of the bot you are using. (Can be found at the top of the bot's code in Tamper/Greasemonkey.)
>      - What you think caused this issue. (On your end, you don't need to diagnose our code, tell us what you did that caused it.)
>      - If you can, suggest a solution. (Again, you don't need to be technical in your description.)

**Comment by tjorim** [comment]
Confirmed, I think it's caused by @FliiFe 's last commit a0148ebc2ca2de416a107178428d01454b2ca0b5

**Comment by tjbcg** [comment]
@tjorim You are probably right.
