### ISSUE TITLE
Is there a version history somewhere, to see changes?

### ISSUE THREAD

**Issue by MiralDesai** [ermiyaeskandary/Slither.io-bot#172]
Would be nice to have I think.

Two ways to potentially go about it:
- Tagging your git commits for each version. Then adding a short description or letting us just see where one version starts and stops in the commit history.
- Update README with this information, although could get quite long. Maybe the wiki?

**Comment by ChadSki** [comment]
You can see the changes over time right here: https://github.com/ErmiyaEskandary/Slither.io-bot/commits/master

Although we haven't been releasing properly formatted changelists with this info...

Want to give it a shot? :) Could be added to the readme.

**Comment by MiralDesai** [comment]
Ah cool, I can certainly give it a go. Bit hard to read each commit though, this is a very active repo. Any ideas on how we can improve that? Lots of "cleaning" from a quick glance at the commit messages.

**Comment by ChadSki** [comment]
Yeah, it was easy to follow along when the code was just 800 lines... it's more than doubled that size in a week!

We're trying to be a bit more organized about things... [#191](https://github.com/ErmiyaEskandary/Slither.io-bot/issues/191)

A better approach might be reading merged pull requests in order: https://github.com/ErmiyaEskandary/Slither.io-bot/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+sort%3Acreated-asc+is%3Amerged

**Comment by clemens-tolboom** [comment]
The last fixes changed so much of the code idea (no decision tree; all into one file) which created a nice bot but it would be nice to have a CHANGELOG.md of some sort explaining the big changes

**Comment by ermiyaeskandary** [comment]
The last changes implement the first system we were using. The multiple file bot was experimenting with A\* path finding and is now in a separate branch...

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom @ChadSki We will from now on do commits with meaningful names with detailed description, which removes the need for a CHANGELOG and `git log` would show every little bit of code changed...
