### ISSUE TITLE
Uncaught TypeError: Cannot read property 'radius' of undefined

### ISSUE THREAD

**Issue by hnphi** [ermiyaeskandary/Slither.io-bot#173]
Console log error: **Uncaught TypeError: Cannot read property 'radius' of undefined**

**Comment by ChadSki** [comment]
Did it work for a short while, then crash? Or did it not work at all?

**Comment by Drflash55** [comment]
I will have to test this out when I get home and see if I get the same error.

**Comment by ermiyaeskandary** [comment]
Latest version ?

**Comment by ermiyaeskandary** [comment]
Shouldn't occur with the latest commits - if it does, please comment with a screenshot and we will reopen...
