### ISSUE TITLE
Suggestions for rapid growth of snake

### ISSUE THREAD

**Issue by pazzl7** [ermiyaeskandary/Slither.io-bot#175]
Hello! I'm pazzl7, and I'm very happy with your work... Although, I have a few suggestions for how your snake can rapidly grow in success _(I'm so sorry, this was not intended to be a pun! I swear! ~ Drflash55)_.

Suggestions for rapid growth of snake :
- Make the snake head to the center very early and have it kill off the other snakes. Then have it play as a defender so it doesn't die quickly.
- Make the snake react quickly to enemies and have it boost aggressively after dead snakes. 
- Make the bot have more of an aggressive behavior later on in the game, such as trapping snakes to kill them... 
- Make the snake avoid walls.

_Edited by ErmiyaEskandary - "translation" and clarification_

_(Added details so that his suggestions were understandable... Sorry if I took it too far. ~ Drflash55)_

**Comment by ROacktree** [comment]
After a certain length focus on worm carcasses instead of spawned food.

Increase avoidance distance as minimal turning radius increases.

(I have seen large snakes 'thread the needle' and live where one would think it not possible.  Is body width not a real factor?)

**Comment by ermiyaeskandary** [comment]
@ROacktree It currently does and did food clustering...

**Comment by Seple** [comment]
and auto option "enable" -> Prey (the fast-moving blinky ones) to 100-1000 points or near head.
and New option Agressive behaviour hunting -> Fast surprise in front of his head #210 
and... #120 + # detect  encircle other snakes + #78

**Comment by Seple** [comment]
- I noticed that the snake grows faster when settings: radiusMult 12 , foodRoundSize : 1
- also it helps, but risky , when a large snake- the turning radius --- > foodSmallSize 4 ,

Please, if this option is possible to add settings stanadrd to 10,000 points ?

**Comment by ChadSki** [comment]
> Make the snake head to the center

@clemens-tolboom 's "go to X,Y" work might be useful here.

**Comment by clemens-tolboom** [comment]
Yeah that could be implemented with #275.

It would require a simple task something like

``` javascript
var growFactor = scheduler.newTask('GrowFactor');
growFactor.getPriority = function() {
  // Your logic
}
// No need to fill in execute as it does not repositions the snake
// No need to set priority
growFactor.active = true;
scheduler.addTask(growFactor);
```

**Comment by clemens-tolboom** [comment]
Original question #266 led to implemention branch #275

**Comment by ChadSki** [comment]
Since this is four separate suggestions in one, and these features are being tracked by other issues, I'm closing this issue for now.
