### ISSUE TITLE
Uncaught TypeError: Cannot read property 'onPrefChange' of undefined

### ISSUE THREAD

**Issue by Tomboman** [ermiyaeskandary/Slither.io-bot#176]
JS Error when right button is pressed:
VM257:376 Uncaught TypeError: Cannot read property 'onPrefChange' of undefined

**Comment by ermiyaeskandary** [comment]
Please edit your issue adhering to this below :

https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

^^^

**Comment by Drflash55** [comment]
@ErmiyaEskandary What he said...

Please edit your issue according to the documentation so it looks formal...

**Comment by ermiyaeskandary** [comment]
@Drflash55 @Tomboman Great example - https://github.com/ErmiyaEskandary/Slither.io-bot/issues/177

**Comment by ermiyaeskandary** [comment]
Still evident ?

**Comment by ermiyaeskandary** [comment]
Not evident anymore...
