### ISSUE TITLE
Unable to dash after using the bot for some time.

### ISSUE THREAD

**Issue by dingyang1988** [ermiyaeskandary/Slither.io-bot#177]
I am using bot version 0.9.3 on Google Chrome Version 50.0.2661.102 m with Tampermonkey on Windows 7.

I noticed that after using the bot for some time, I am unable to dash with the left mouse button. Clicking and holding the left mouse button will use up only 1 point of my length and the snake will just light up very very briefly, with a dash that is barely noticeable. Pressing and holding space bar gives me variable results, sometimes I am able to dash, sometimes not.
I am unable to pinpoint the exact steps to reproduce this issue, but it happens usually after I use the bot for some time. Restarting the game doesn't resolve the dashing issue. To resolve the issue, I will have to close that tab/window and restart the game in a new tab.

Not sure if the following information will be useful, but I'll just provide some details regarding my pattern of bot usage, hope it helps with the process of reproducing the bug.

I use the bot mainly during the boring early phases of the game to gain to a length of a few hundred before taking over control from the bot. The options that I have enabled are visual debugging, auto respawn, mobile rendering and collision detection. Collision radius multiplier is set at 10. I sometimes have 2 or 3 slitherio games running concurrently in different windows so that I always have at least one bot with a good length that is ready for me to take over control. 
Previously I had other slitherio extension installed, but the issue still persists despite disabling all other extensions and I do not have other userscripts installed in Tampermonkey.

Hope this helps. Thank you.

**Comment by ermiyaeskandary** [comment]
@dingyangheh Great example of a detailed bug report. :)

Will look into it - surely helps. Thanks again :+1:

**Comment by dingyang1988** [comment]
If you are unable to reproduce the bug with the above steps or need any additional information please let me know. 

Will it help if I enable log debugging? Where can I find the log?

**Comment by Drflash55** [comment]
@dingyangheh If you enable log debugging, all of what it feeds is put into the console, which on Google Chrome, you can access by pressing the hotkey (CTRL+SHIFT+J).

**Comment by ermiyaeskandary** [comment]
@ChadSki Read the wiki - :)

**Comment by ChadSki** [comment]
> Title: Start title with [Bug](Helps with labeling)

Oh... What's the point of [square bracket] tags when we have real tags?

For those without permission to add tags, using [square brackets] make sense... but shouldn't they be replaced with labels later?

Anyway I'll stop editing titles that way for now.

**Comment by ermiyaeskandary** [comment]
@ChadSki My mistake - sincere apologies 

> be replaced with labels later

**Comment by tjorim** [comment]
@dingyangheh With dash, do you mean speeding the snake? If so, the acceleration can not be used when the bot is on.

This has been like this since the beginning since the bots constantly checks if it should speed up, for now it just does not.

**Comment by ermiyaeskandary** [comment]
@dingyangheh Can you test the latest version ...

**Comment by dingyang1988** [comment]
@tjorim 
The bot was disabled when this issue occurs.
Usually, I would have full control of the snale when the bot is disabled, i.e. direction of movement, acceleration. 
Sometimes after using the bot for some time, I can't accelerate even after disabling the bot, which require me to start a new window/tab to resolve. 

@ErmiyaEskandary
I'm at work right now. Will try it out tomorrow afternoon after I get off work. (I'm in +8GMT time zone btw). Will update. 
Thanks

**Comment by ermiyaeskandary** [comment]
Can someone test ?

**Comment by dingyang1988** [comment]
I'm testing v0.9.6 now. Bot has been running for about half an hour now, yet to encounter this problem. Will leave the bot running for longer, see if the problem recurs.

**Comment by dingyang1988** [comment]
@ErmiyaEskandary I have managed to reproduce the bug in version 0.9.6 and this time I have log debugging enabled. This should shed some light on the bug. 

Here's a video demonstrating the bug
https://www.youtube.com/watch?v=Ezrmf6dNe3Q

0:25-0:51 shows a normal game play. I am able to dash with no issue.

0:55 onward shows game play with the bot affected by the bug. The HUD on the left appears to indicate that the bot is enabled, when it is actually not. Notice that the snake is still following my mouse pointer despite the HUD indicating the bot being enabled. The debugging log is showing that the bot is constantly being restarted and stopped, when in fact I wasn't pressing any button to enable or disable it. Notice that when I tried pressing the left mouse button for manual boosting, the snake just lights up briefly and then stops. For some unknown reason, the bot is automatically being enabled and disabled as indicated in the debugging log, which I think is the cause of the manual boosting bug.

Hope this helps.

**Comment by dingyang1988** [comment]
Manage to reproduce the bug for the second time now. Unable to manual boost after leaving the bot running for some time, and same as in the video, the problem starts when the bot somehow got into a loop of auto starting and stopping itself.

**Comment by ermiyaeskandary** [comment]
Should be fixed now - can someone test and feed back ?

**Comment by dingyang1988** [comment]
Testing the bot now, so far no encounter with this bug yet for 1 hour or so? Since I'm not sure of the exact steps to reproduce bug, will need a little more time to confirm that it doesn't recur.

**Comment by ermiyaeskandary** [comment]
If it happens again, please reopen :+1: 
Cleaning up issues..
