### ISSUE TITLE
Add collision prevention

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#18]
Bot should treat snake bodies and the map border as obstacles, but treat heads as active threats.

Maybe have a mimicry form of self defense?

**Comment by ermiyaeskandary** [comment]
@flying_platypus ideas:

> I think the snake tails should be avoided but not completely so that the the bot could be almost skim it
> 
> Also if the snake head(enemy) is moving towards the head of your snake the bot should weave away from the snake.
> 
> Also maybe it should copy the movements of the opponent snake as a defense maneuver.

**Comment by ermiyaeskandary** [comment]
@Evanito ideas:

> Treat snake bodies as obstacles like the map border, but actively avoid snake heads

**Comment by ermiyaeskandary** [comment]
@FliiFe ideas:

> The logic would be to scale up every component of the snakes (made out of circles), and then turn when entering one of those scaled elements

**Comment by ghost** [comment]
@FliiFe why would you scale up snake tails? you do not need to stay far from them you can literally be as close as you want to them just not touch them. snake heads on the other hand.. that would be different. but yes the snakes themselves should definitely be obstacles.

**Comment by ermiyaeskandary** [comment]
We need to find a way to make them obstacles. But then after that, we need to find the variables needed.

**Comment by ghost** [comment]
hmm i just realized that bigger snakes make wider turns... that means they have to start turning earlier for bigger snakes than small snakes..

**Comment by haylinmoore** [comment]
Hmm so it needs to do math for the turn radis based on the size of the snake. Also remember sprints can be used to turn and move faster

**Comment by haylinmoore** [comment]
So will it avoid snakes yet?

**Comment by ermiyaeskandary** [comment]
Reviewed status - check the wiki for more info

**Comment by Drflash55** [comment]
Yep, this is still an issue I'm seeing.

When the bot is going after prey, it doesn't take into consideration the other snakes around it, thus it runs straight into them.

I wonder when this thing will be coded in so that I can do some test runs on how well it can avoid other enemies.

**Comment by K00sKlust** [comment]
we shouldn't size up the other snakes, but a copy of our snake. That's just one object to rescale :)
Like:

```
var snakeCopy = Object.assign({}, snake);
snakeCopy.sc += 0.1;
```

**Comment by tjbcg** [comment]
Should we really rescale things ? I think we should just put a circle around every snake head, and avoid them as much as possible, and choose wether the bot can eat food depending on its accessibility

**Comment by ermiyaeskandary** [comment]
What he said - we can make snake body obstacles and then the head an active threat. 

> Treat snake bodies as obstacles like the map border, but actively avoid snake heads

**Comment by K00sKlust** [comment]
I mean we could use the rescaling for obstacles, not for _active_ avoiding.

**Comment by tjbcg** [comment]
> choose wether the bot can eat food depending on its accessibility

That would solve obstacle avoiding, wouldn't that ?

**Comment by ermiyaeskandary** [comment]
@FliiFe Yeah - more or less

**Comment by chancity** [comment]
snake.pts where dying = true are the snake parts that need to be avoided.

snake.sc_15_w.gsc seems to give me a good circle radius for drawing the parts on the canvas.

**Comment by chancity** [comment]
snake.sc_15_w.gsc

**Comment by chancity** [comment]
Snake.sp and snake.msp are used for calculating snake speed...

**Comment by ermiyaeskandary** [comment]
Great - We will take this into account.
Thanks!

> snake.pts where dying = true are the snake parts that need to be avoided.

**Comment by ermiyaeskandary** [comment]
Temporary solution with the latest update. Issue still open till angles get implemented.

**Comment by ermiyaeskandary** [comment]
Please read #22. Angles will not be implemented. Issue closed and additional issues will be opened for optimising current enemy code.
