### ISSUE TITLE
Four observations about movement algorithm

### ISSUE THREAD

**Issue by duncanhoward** [ermiyaeskandary/Slither.io-bot#184]
Choosing the right direction to go. 

1) The value of any given path - does this include the food value of any intervening food between snake and selected target?  If it did, the snake would want to follow lines of food and generally take greater advantage of food formations?

2) Snake chooses one path but before it eats, it chooses another.  And then before it eats, it chooses another.  Maybe up the priority of currently selected target somehow to reduce the tendency to keep changing targets but not getting any food?

2) Circular, non-advantageous coil when chasing down food.  Snake locks on to food, but can not turn tightly enough to capture.  Repeat until snake is a tiny little coil.  If food is too close to make the turn, maybe skip it for the time being.

3) Collision avoidance.  Seems that snake often makes the less advantageous choice when turning away.  If collision avoidance is activated and the choice is immediate "turn right" vs "turn left",  going where there is less other snakes might be good.

Thank you for listening and for a really fun toy!

**Comment by ROacktree** [comment]
Under length Z bot && safe distance from other snakes.. bot should favor avoiding paths with no food.

^ less safe distance.. bot should avoid straight paths

**Comment by ermiyaeskandary** [comment]
@duncanhoward I'm quite sure the current version does all the things you have listed... If i'm wrong, please comment and I will reopen...

_Cleaning issues..._
