### ISSUE TITLE
Toggle visibility of HUD

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#185]
I would love to see a Overlay/HUD hide function

**Comment by ghost** [comment]
Seems a good idea

**Comment by ermiyaeskandary** [comment]
So like a button to toggle the overlay ?

**Comment by Salvationdk** [comment]
or a hotkey.. [TAB] maybe or H

**Comment by tjorim** [comment]
I was thinking of using something like a Bootstrap Modal.

**Comment by ermiyaeskandary** [comment]
@tjorim http://www.w3schools.com/jsref/prop_style_visibility.asp 

A Bootstrap Modal would be too bloated IMO

**Comment by Salvationdk** [comment]
New version as of today is using H as hide HUD, so closed for now
