### ISSUE TITLE
Quick respawn doesn't automatically start bot

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#188]
Bot says enabled on respawn wih [ESC], but must press T to enable manually

**Comment by Drflash55** [comment]
Well, well... They're just popping up everywhere...

@ErmiyaEskandary Can you replicate this bug?

**Comment by ermiyaeskandary** [comment]
@Drflash55 

> Well, well... They're just popping up everywhere...

:+1: XD - it's code....

**Comment by ermiyaeskandary** [comment]
@Salvationdk Fixed ?

**Comment by Salvationdk** [comment]
@ErmiyaEskandary nope

**Comment by ermiyaeskandary** [comment]
Does it respawn with the bot on if you click ESC when the bot is enabled or
when the bot is disabled and you respawn this happens ?

**Comment by Salvationdk** [comment]
if bot is disabled and i press ESC it restarts with bot enabled and working

If i press ESC while bot is enabled, it respawns enabled but not working

**Comment by ermiyaeskandary** [comment]
What do you mean by not working ?

**Comment by ermiyaeskandary** [comment]
> if bot is disabled and i press ESC it restarts with bot enabled and working

Did I fix it or was it like this ?

**Comment by hnphi** [comment]
@ErmiyaEskandary Me too,
**Enable** bot -> Play game -> Press **ESC** -> Game restart -> Bot stop working (but still show **Enable**)

**Comment by Drflash55** [comment]
@ErmiyaEskandary From what I read on here...

If you enable the bot in the main menu, and you play the game, when you press Escape, the game will restart, but the bot will no longer be functioning (although the bot thinks it's still on)

If it's disabled, it has no problems... Should try to look for the error that's causing the quick respawn function to disable the bot entirely...

**Comment by tyschnoor** [comment]
@Salvationdk You have to click **Start** for the bot to start it's auto-respawning

**Comment by ermiyaeskandary** [comment]
Fixed ? Can you test with the latest code ? @tyschnoor @Drflash55 @pomega @Salvationdk

**Comment by Drflash55** [comment]
@ErmiyaEskandary Ugh, sorry... Not available as of right now...

**Comment by Salvationdk** [comment]
working as of new version so closed
