### ISSUE TITLE
Make the bot turn in a perfect circle as defense

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#19]
When enemies are near, we could just turn in a perfect circle until they give up. This could prove successful as we can go in a perfect circle using programming but they can't - and eventually they will give up.

**Comment by ghost** [comment]
i dont think that will work i have actually watch the bot with the (food circle bug) make perfect circles and get eaten by a bigger snake. its kinda hard to explain but il tell you that it is possible to get destroyed while doing a perfect circle

**Comment by ermiyaeskandary** [comment]
If you are a certain length, and you do a *perfect \* circle, this is possible.

**Comment by tjbcg** [comment]
@ErmiyaEskandary If enemy circles you, then you're finished, since loops get tighter as the snake go

**Comment by ghost** [comment]
yes thank you i didnt know how to explain that @FliiFe

**Comment by ermiyaeskandary** [comment]
What do you mean it gets tighter ? If you are in a perfect circle, what is the other snake going to do ? He can't touch you as you are in a perfect circle where your head is on our body at all times.

**Comment by tjbcg** [comment]
I think if a snake's body loop tightens on you, then **you** are going to die

**Comment by Drflash55** [comment]
@FliiFe It all depends if the snake goes in at an angle that causes the length of the snake to close in, which in that case, there's no way to live, unless they get cocky and kill themselves in the process...

**Comment by tjbcg** [comment]
After some observations, you cannot really turn in a perfect circle under a certain radius.  If you want the circle to be as tight as possible, your head will always be slightly outside of the circle

**Comment by haylinmoore** [comment]
A perfect circle would protect from someone circling around you.

**Comment by dracco1993** [comment]
#47
