### ISSUE TITLE
The master branch is too volatile

### ISSUE THREAD

**Issue by ChadSki** [ermiyaeskandary/Slither.io-bot#191]
So far, collaborating has been a little challenging. Usually one developer will build up massive changes over several days, then get a massive merge into master.

Master is supposed to be stable, but we've been merging stuff ahead of release quality because we need to "land" the feature in order to collaborate on it.

I propose that we start using multiple branches on this repo.

`ErmiyaEskandary/Slither.io-bot/master` should always be working, effective, stable, minimal bugs.

`ErmiyaEskandary/Slither.io-bot/develop` is where we prepare changes for merging into master.v

We can create other feature branches as well. Branches such as `feature-astar` or `feature-refactor` can be spun up as needed.

This diagram is pretty good, although I don't think we need multiple release branches, or a hotfix branch. My main goal is to keep master a little more protected from development churn.

![git branching strategy diagram](http://lanziani.com/slides/gitflow/images/gitflow_1.png)

What do you think?

**Comment by ermiyaeskandary** [comment]
Approved

**Comment by Drflash55** [comment]
This seems like a good idea... You can have branches that will constantly be updated with features that are still beta, and then when they're stable enough, it can get merged into the Master branch...

**Comment by ermiyaeskandary** [comment]
Agreed - doing this from now on. We currently have different branches
waiting to be confirmed and fixed to get merged into master...

**Comment by ChadSki** [comment]
Cool. Let's close the issue, then!
