### ISSUE TITLE
[Bug] No food vs. grid system.

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#194]
When there is no food in the outer areas of the map, the worm collides with outer wall. It simply just keeps going straight.

**Comment by ermiyaeskandary** [comment]
**Duplicate** of #72 : 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.
