### ISSUE TITLE
The ability to change individual defense ranges

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#195]
Hay ;)

Please comback 
Better Version -> https://github.com/ErmiyaEskandary/Slither.io-bot/commit/04a307e42b8b2c06b5063a01e3c67cc292358f18 and https://github.com/ErmiyaEskandary/Slither.io-bot/blob/f4f16ff292c8bfdba703bf922bdedc1cbf62d1e1/bot.user.js

Manual Option - (comfortable "Circle").
- [A / S] Keys for body avoidance collision radius
- [E / R] Keys for head avoidance collision radius

...and fix
[P] Hunt prey (Moving food)
- Auto - to the (lower) lvl 100

...and fix
Please fix "new option" - Bot is not aggressive enough about going after big piles of food #94

...end fix
New "Defense mode" #78

I think the Perfect BOT :D

**Comment by Drflash55** [comment]
As I see here, you're suggesting to have keys that can manually change the collision radius for both the head and body of a snake...

@ErmiyaEskandary Would this be possible to code in at all?

**Comment by Seple** [comment]
> As I see here, you're suggesting to have keys that can manually change the collision radius for both the head and body of a snake... @ErmiyaEskandary Would this be possible to code in at all?

Yes of course. You understood me ;) Readable graphic and better comfortable tuning ...and so on ;)

PS. Maybe Menu Start confing and 2. Menu Play game (Menu during the game)?

**Comment by Seple** [comment]
Solved with the new version Please closed topic :)
