### ISSUE TITLE
Bot lags

### ISSUE THREAD

**Issue by tjbcg** [ermiyaeskandary/Slither.io-bot#20]
Am I the only one to notice huge lags  ? It's fine in the beggining, and gets worse over time

**Comment by ermiyaeskandary** [comment]
@FliiFe Comment out all code related to enemy detection and ... 
This fixes it

**Comment by tjbcg** [comment]
@ErmiyaEskandary Still have this issue. I have the commented out version

**Comment by tjbcg** [comment]
@ErmiyaEskandary Was not lagging yesterday

**Comment by ermiyaeskandary** [comment]
@FliiFe Could you find with which commit the lag is caused ? I'm working on prioritizing big food right now.

**Comment by tjbcg** [comment]
@ErmiyaEskandary Sure

**Comment by ermiyaeskandary** [comment]
@FliiFe Thanks
