### ISSUE TITLE
Laggy

### ISSUE THREAD

**Issue by tyschnoor** [ermiyaeskandary/Slither.io-bot#201]
When I run the mod, slither.io is very slow on **ONE** of my computers, on the other one it works better but still a little slow.

**Comment by ermiyaeskandary** [comment]
Have you tried mobile rendering? Can you post an image of your specs? We are always thinking about performance when coding and are constantly trying to improve it...

**Comment by tyschnoor** [comment]
@ErmiyaEskandary I will try

**Comment by tyschnoor** [comment]
@ErmiyaEskandary I recorded a video; just [Click Here.](http://youtu.be/BL4ToRsF5RA?hd=1)

**Comment by dingyang1988** [comment]
I think some info on your computer specs will help..
For me slither.io is more laggy when played on firefox, and much smoother in chrome. 

And you appear to be using an older version of the bot, maybe try updating to the newest version?

**Comment by tyschnoor** [comment]
@dingyangheh Okay. I will try that. 

**NOTE:** I am on Google Chrome

**Comment by dingyang1988** [comment]
The game does appear to lag a lot for you. Does it lag too when you play it without the bot? What is the FPS like when the bot isn't enabled?
Try pressing O to enable mobile rendering. I find that it helps quite a bit with the performance.

**Comment by tyschnoor** [comment]
@dingyangheh It does lag without the bot and when I press O, it does nothing.

**Comment by dingyang1988** [comment]
Pressing O should enable mobile rendering which will turn the screen into something like this 

![](https://slitheriogameplay.com/wp-content/uploads/2016/05/slither-io-mod-sgp-new-2-min-660x330.jpg)

At least it does so in the current version.... Not sure if it's the same for older versions?

**Comment by tyschnoor** [comment]
@dingyangheh Let me try and see if I have to update the mod.

EDIT: I updated it. Trying it now.

**Comment by tyschnoor** [comment]
@dingyangheh @ErmiyaEskandary I updated it, I turned on Mobile Rendering, but now I can't turn on the bot. :-1:

**Comment by ermiyaeskandary** [comment]
Yeah - it is evident from the video that you are using an old version.

**Comment by ermiyaeskandary** [comment]
@tyschnoor You can't turn it on ? What do you mean ?

**Comment by tyschnoor** [comment]
@ErmiyaEskandary I just updated it though.
Now I can't turn the bot on.

**Comment by tyschnoor** [comment]
I mean, my computer is really bad, maybe it's just the computer?

**Comment by ermiyaeskandary** [comment]
> Now I can't turn the bot on.

**Comment by ermiyaeskandary** [comment]
Slowness aside - does the bot work ?

**Comment by ermiyaeskandary** [comment]
You need to install bot.meta.user.js, not bot.user.js

**Comment by tyschnoor** [comment]
How do I do that?

**Comment by dingyang1988** [comment]
Uninstall the current version installed and install the bot.meta.user.js

Here's the link
https://github.com/ErmiyaEskandary/Slither.io-bot/raw/master/bot.meta.user.js

**Comment by ermiyaeskandary** [comment]
Uninstall all scripts you have and go through the text tutorial on the README.

**Comment by tyschnoor** [comment]
Can you please link me to that??

EDIT: I mean the README

**Comment by ermiyaeskandary** [comment]
https://github.com/ErmiyaEskandary/Slither.io-bot/raw/master/bot.meta.user.js

**Comment by ermiyaeskandary** [comment]
@tyschnoor BTW, it'd be good if you joined our Gitter chat here : https://gitter.im/ErmiyaEskandary/Slither.io-bot

**Comment by ermiyaeskandary** [comment]
@tyschnoor Remove all scripts you have and then click on this : https://github.com/ErmiyaEskandary/slither.io-bot/raw/master/bot.meta.user.js

Choose install and then go to slither.io :+1:

**Comment by ermiyaeskandary** [comment]
It should work

**Comment by tyschnoor** [comment]
IT WORKED!! :+1: :raised_hands: :
