### ISSUE TITLE
What if there was a.... Disable Leaderboard Feature?

### ISSUE THREAD

**Issue by tyschnoor** [ermiyaeskandary/Slither.io-bot#202]
Wouldn't be cool if there was a **Disable Leaderboard** option? That would be very good for kids.

EDIT: My friends' siblings always play on slither.io and their older sibling has to watch over them for usernames.
OTHER IDEA: You could include that in this mod or create another.

**Comment by ermiyaeskandary** [comment]
Easy to do :) - selfassigned

**Comment by ErmiyaEskandary** [comment]
What letter do we prefer ?

**Comment by ermiyaeskandary** [comment]
@tyschnoor What letter do you prefer ?

**Comment by Drflash55** [comment]
@ErmiyaEskandary You can use the U Key, since nothing else has occupied that slot...

**Comment by tyschnoor** [comment]
@ErmiyaEskandary How do you assign it?

**Comment by ermiyaeskandary** [comment]
@tyschnoor What do you mean?

**Comment by Drflash55** [comment]
@ErmiyaEskandary He was basically asking you how you assign the key so that it disables the leaderboard.

**Comment by Salvationdk** [comment]
So this means you want to disable usernames not appropriate for young kids?

**Comment by tyschnoor** [comment]
@Salvationdk Yes

**Comment by Salvationdk** [comment]
I dont really think this is the right plugin to have this. This is a bot not a mod..

**Comment by tyschnoor** [comment]
​I guess. But I just thought it would be cool. Or if the bot censored the
bad usernames.

**Comment by Drflash55** [comment]
There could be a separate mod that could be made that turns off the usernames... Doesn't have to be implemented with the bot...
