### ISSUE TITLE
Snake's eyes green sometimes

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#21]

**Comment by tjbcg** [comment]
Potentially fixed with last commit. Needs testing

**Comment by ghost** [comment]
I still see green snake eyes

**Comment by tjbcg** [comment]
We all do @TheFlyingPlatypus . Unfortunately, we don't know why this is caused (as for #17).

**Comment by ermiyaeskandary** [comment]
Also happens for border. Hint ?

**Comment by tjbcg** [comment]
I think it is caused by the property `strokeStyle` of canvas' context.  That's what I tried to do with b5f4c7c, but it looks like the change has to be applied (committed) on the context.

**Comment by tjbcg** [comment]
That would explain why only the border of the snake's eyes are green

**Comment by ChadSki** [comment]
Is this still an issue?

**Comment by ermiyaeskandary** [comment]
Haven't seen it happening...

**Comment by Drflash55** [comment]
So... I guess this has been fixed, and can be closed...?
