### ISSUE TITLE
Error with Google Chrome

### ISSUE THREAD

**Issue by hnphi** [ermiyaeskandary/Slither.io-bot#212]
Script Bots not working on my browser (Google Chrome). I very try so much, but it still not working.
[http://i.imgur.com/BvVB2dA.png](http://i.imgur.com/BvVB2dA.png)
I was install bots step-by-step like below:
Step 1: Install Tampermonkey.
Step 2: Access link in README [here](https://github.com/ErmiyaEskandary/slither.io-bot/raw/master/bot.meta.user.js)
Step 3: Go to slither.io to play.

**Comment by ermiyaeskandary** [comment]
One min

**Comment by Drflash55** [comment]
Huh... Didn't know one little parentheses could mess up the entire script...

**Comment by ermiyaeskandary** [comment]
@Drflash55 Syntax error :+1:
