### ISSUE TITLE
Skin changer (auto and manual)

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#213]
Please add an option to rotate the skin - W and X

...and perhaps at the same time to optimize the code for the bot , so it is less CPU -intensive and gives a decent FPS = " skinny " ( slimming ) version?

**Comment by ermiyaeskandary** [comment]
Apparently , skin change is only client side ?

**Comment by ermiyaeskandary** [comment]
And IMO it is in other mods - we aren't here to just copy stuff.... Sorry for being so blunt @Seple :+1: But I'll go with what other people think ...

**Comment by Seple** [comment]
betther ONE skprypt - than some script that does not fit "a few to bite script" 
understand?

**Comment by ermiyaeskandary** [comment]
I'm sorry but I don't understand.... :(

**Comment by Seple** [comment]
I think better (all option skin) ONE SCRIPT than than a few several (more) script's 
---> in other words: everything in one script code ...instead "several other more" script code

...but still strive to lose weight code = " skinny " ( slimming ) version and optimization CPU - FPS

I am sorry for my language english :(
understand?

**Comment by ermiyaeskandary** [comment]
Understood but a skin changer isn't vital to a bot IMO and it would just be adding lines to the code

**Comment by ermiyaeskandary** [comment]
What do other people think ?

> Understood but a skin changer isn't vital to a bot IMO and it would just be adding lines to the code
> 
> I'll go with what other people think

**Comment by tjorim** [comment]
We already had it so we could keep it, I tried a few mods but they might interfere with our keycodes.
If saying people could simply use other scripts, they might as well use one for custom server selection: https://github.com/LukeeeeBennett/slither-nest

**Comment by ermiyaeskandary** [comment]
@tjorim I understand your point but what I'm saying is that we don't just sit here copying mods which are available in other mods... The point about them not being compatible is another thing...

**Comment by ermiyaeskandary** [comment]
@tjorim Anyway, more than 3 votes and we can add them back in ...

**Comment by Seple** [comment]
OK  Voting

**Comment by Seple** [comment]
Please people New Voting #71  
Who agrees ? Thumbs up or thumbs down

**Comment by ermiyaeskandary** [comment]
Any votes ?

**Comment by ChadSki** [comment]
:-1: I'm happy with the skins we have now. I care more about improving the bot AI than tweaking the skins.

**Comment by Seple** [comment]
topic expired 
better improve the functions of defense and flee mode and attack
please close topic
