### ISSUE TITLE
Food Cluster Dashing.

### ISSUE THREAD

**Issue by SlitherHeatwaVe** [ermiyaeskandary/Slither.io-bot#214]
Hello. I have found that the new bot of 9.7 has been dashing for cluster food now. I think that the bot might be calculating as if it were normal speed, just a thought. But it is definitly going out of whack when it is dashing for food. as i understand it, in grid view, the blue boxes is the worm to avoid, and the worm turns away when it goes inside the area. When the bot finds the cluster of dead worm food, it starts zig zagging around while dashing, causing the food pickup to be very inefficient. 

Thanks for listening =)

**Comment by ermiyaeskandary** [comment]
We have now switched to a different system - I'm sorry but what is your request in simple terms ?

**Comment by SlitherHeatwaVe** [comment]
It goes for food, it dashes in zigzag directions, misses a lot of food that is later picked up by nearby worms.

Is it possible to make the pickup in a more general way, like just cutting straight through the middle and then avoiding people when their body is in the way?

Thanks

**Comment by Salvationdk** [comment]
This is no longer an issue.
