### ISSUE TITLE
Chrome/Iron browser jerking fix

### ISSUE THREAD

**Issue by pllsner** [ermiyaeskandary/Slither.io-bot#215]
// @version 1.0.0 
...........................................................................................................................................................
1190   oefTimer: function() {
1191           var start = Date.now();
1192            canvas.maintainZoom();
1193            original_oef();      <----------------------- comment this out.  1193  // original_oef();
1194            original_redraw();
............................................................................................................................................................
original_eof(); causes my  browser screen to jerk  back and forth an inch or two. even while running bot. so i removed it. screen runs smooth now.

**Comment by ermiyaeskandary** [comment]
@ChadSki @tjorim @j-c-m Is this needed or can it be commented out ?

**Comment by pllsner** [comment]
hello,  
line 1193: original_oef();
of  @version      1.0.0  was causing problems in my iron browser. so i commented it out. seems the screen was trying to be redrawn twice, but with coordinates offset. by removing line 1193. script runs smooth now. have not tried this in firefox browser. other scripts based on ErmiyaEskandary's gave screen jerking also. ever since game updated it's engine 2 days ago, i was having issues. commenting out that line fixed the issue in those scripts as well. seems the call to
original_oef(); is not required.
i editted original post to clear up any confusion.

**Comment by ermiyaeskandary** [comment]
@pllsner Can you post screenshots of fps before and after commenting out that line ?

**Comment by ermiyaeskandary** [comment]
@pllsner Apparently, it doesn't cause an FPS change :+1:

**Comment by ermiyaeskandary** [comment]
@pllsner I can check personally later

**Comment by pllsner** [comment]
after uncommenting line 1193. screen issues have vanished. cleared my browser cache to reproduce problem. now it runs normal. perhaps it was  server lag causing the stuttering.
whatever has caused it, line 1193 seems redundant code. so i commented it out.  script runs perfect with or without line 1193. hope this is of some help.

**Comment by ermiyaeskandary** [comment]
:+1:
