### ISSUE TITLE
Custom server selection

### ISSUE THREAD

**Issue by phrokton** [ermiyaeskandary/Slither.io-bot#216]
Please consider integrating the feature.

Adds a second start button with dropdown option of server addresses, or manual entry.  Found at one of those sites which strips attribution.

![snakeinthegrass](https://cloud.githubusercontent.com/assets/19551366/15502692/777ac4e4-216a-11e6-9b4a-7ccc9b99b365.png)

[pastebin--tmp--sgpmodv7.js.txt](https://github.com/ErmiyaEskandary/Slither.io-bot/files/279384/pastebin--tmp--sgpmodv7.js.txt)

**Comment by Drflash55** [comment]
I approve of this suggestion. It would be nice to have a feature that allows you to join a custom server...

**Comment by Salvationdk** [comment]
And party code. So you can join your friends..

**Comment by tjorim** [comment]
Kinda duplicate of #139 , you should comment your suggestion there.
