### ISSUE TITLE
tinkering on the fly, non-edit

### ISSUE THREAD

**Issue by phrokton** [ermiyaeskandary/Slither.io-bot#217]
GreaseMonkey has a feature for commands.  Click toolbar icon.  Options are visible for scripts featuring such.  I am unaware of a tampermonkey analog.  More hotkeys seems like ui clutter.  Maybe a hotkey to show many tinkering values

Either case please move to top of the user script the variables for tinkering.

**Comment by ermiyaeskandary** [comment]
**Duplicate** of #185 : 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.
