### ISSUE TITLE
do you have?

### ISSUE THREAD

**Issue by eralpcicekdagi** [ermiyaeskandary/Slither.io-bot#218]
can you give me your skype adress?

**Comment by ermiyaeskandary** [comment]
Who's and why ? :confused:

**Comment by eralpcicekdagi** [comment]
i am eralp and need to talk fast online

**Comment by ermiyaeskandary** [comment]
https://gitter.im/ErmiyaEskandary/Slither.io-bot

**Comment by ermiyaeskandary** [comment]
We are all on there
