### ISSUE TITLE
Tampermonkey warning: const is available in ES6.. or Mozilla JS

### ISSUE THREAD

**Issue by phrokton** [ermiyaeskandary/Slither.io-bot#226]
![line17](https://cloud.githubusercontent.com/assets/19551366/15545778/6add9ffc-2252-11e6-88a3-55b32a024e3d.png)

same as lines

128
129
452
617
618

Chromium Version 48.0.2564.116 (64-bit)  &&  50.0.2661.102  (64-bit)  
Tampermonkey 4.0.69

osx: http://freesmug.org/chromium
windows: http://chromium.woolyss.com/  (with webrtc or without webrtc)
windows alternative:  https://chocolatey.org/packages?q=chromium

**Comment by ermiyaeskandary** [comment]
Not important...

**Comment by phrokton** [comment]
Thank you for your swift reply.
