### ISSUE TITLE
use Alex's visual debugging overlay: limited rear view around head

### ISSUE THREAD

**Issue by phrokton** [ermiyaeskandary/Slither.io-bot#228]
https://github.com/AlexJey/Slither.io-bot/blob/master/bot.user.js 

Since his bot does not currently function I could not take a screenshot.  But his snake has limited hindsight -- so that's more than visual debugging; that's logic too.

**Comment by ermiyaeskandary** [comment]
That's the same code as the code in the A\* branch..

**Comment by phrokton** [comment]
His overlay shows a bowtie in a circle as the innermost circle.

**Comment by ermiyaeskandary** [comment]
Are you sure ? Looks the same and the commits do not show a major difference

**Comment by phrokton** [comment]
> Are you sure ?

Not anymore. :O  I will try each of the other userscripts _when they are functional again_ and grab a screenshot.

**Comment by ermiyaeskandary** [comment]
What's functional? The current code in the A\* branch, which is the base code used for the fork you have linked above, is fully functional ...

**Comment by phrokton** [comment]
UserScript other than linked- or in your repo.

**Comment by ermiyaeskandary** [comment]
> The current code in the A\* branch, which is the base code used for the fork you have linked above, is fully functional

That fork is probably old then..

**Comment by ermiyaeskandary** [comment]
> His overlay shows a bowtie in a circle as the innermost circle.

Ah - you mean the red danger angles ? They have now been replaced with circles...
