### ISSUE TITLE
Food cluster calculation

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#23]
Cluster food together that is within one snake radius from the cluster center and calculate distance from that to optimize calculations and fix priorities.

Todo list:
- [x] Calculate our snake's width
- [ ] Use width to make clusters
- [ ] Add value to clusters and do calculations on clusters as a whole.
- [ ] Have bot target clusters

Okay here's a mockup for how I would do this:

Algorithm to check if point is within circle: `(x - center_x)^2 + (y - center_y)^2 < pickup_radius^2` 
1. Start with all of the points in the _unassigned_ group. 
2. Pick one point and look at all the others in the unassigned group and see whether they are within 1 snake pickup radius (I think this is bigger than the visual radius.) 
   1. If yes, start a group, and continue on with all the other points to see if they fit in this group (based on starting point), and if they fit in, move them from the unassigned group into this new one. 
   2. But, if no point matches the criteria for a starting point, use the starting point as a cluster of one. 
3. At the end we will have grouped the points by radius.
4. Sum the sizes of the food in the cluster.
5. Find the distance of the cluster by finding the weighted center of the cluster and check distance from there.

After this, I think we should calculate clusters separately from calculating which one to target, clustering only once per few seconds.

Alternatively, we can base our code of off Apostolique's bot:

```
window.clusterFood = function(foodList, pickupRadius) {
        var clusters = [];
        var addedCluster = false;
        //1: x
        //2: y
        //3: size or value
        //4: Angle, not set here.
        for (var i = 0; i < foodList.length; i++) {
            for (var j = 0; j < clusters.length; j++) {
                if (window.getDistance(foodList[i][0], foodList[i][1], clusters[j][0], clusters[j][1]) < pickupRadius) {
                    clusters[j][0] = (foodList[i][0] + clusters[j][0]) / 2;
                    clusters[j][1] = (foodList[i][1] + clusters[j][1]) / 2;
                    clusters[j][2] += foodList[i][2];
                    addedCluster = true;
                    break;
                }
            }
            if (!addedCluster) {
                clusters.push([foodList[i][0], foodList[i][1], foodList[i][2], 0]);
            }
            addedCluster = false;
        }
        return clusters;
    };
```

**Comment by Evanito** [comment]
Can we look at apostolique's agar.io bot for cluster code?

**Comment by ermiyaeskandary** [comment]
#22

**Comment by ermiyaeskandary** [comment]
My idea at core is taking the average of two x and y coordinates and adding their values for ALL food around. By all, I mean all food must go into a cluster. We then pick the best cluster based on its value and distance to go to. We can't just base our choice on one cluster as, if we are using distance as well, the further away ones are less useful as they have a higher chance of getting eaten.

**Comment by ermiyaeskandary** [comment]
We might be able to work out snake's width from the snake's head ?!

**Comment by chancity** [comment]
Snake.sc x 15 x gsc = snakewidth

I think the clustering should work as follows...

Find food, check the perimeter of that food based off width of snake, check the perimeter of the food in that perimeter so on and so fourth.

**Comment by ermiyaeskandary** [comment]
#22 being worked on _actively_ :)

**Comment by ermiyaeskandary** [comment]
Not using angles. Read #22. 
We need to use the checklist and we could implement it soon hopefully.

**Comment by ChadSki** [comment]
[Pull 86](https://github.com/ErmiyaEskandary/Slither.io-bot/pull/86) probably fixes this, but it uses a hardcoded distance of 100 to do the clustering. It might be better to cluster based on snake width, as @Evanito suggested.

**Comment by ermiyaeskandary** [comment]
Where is the hardcoded distance of 100 ?

**Comment by ChadSki** [comment]
https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/bot.user.js#L485

**Comment by ermiyaeskandary** [comment]
Done with latest PR merge...
