### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by kiri0140** [ermiyaeskandary/Slither.io-bot#232]
the bot dosent work it just goes in a straight line

**Comment by hnphi** [comment]
Remove current script code.
Try again with user code [here](https://github.com/ErmiyaEskandary/Slither.io-bot/raw/master/bot.user.js)
P/S: @ErmiyaEskandary don't forget update link in **README.md**  . And new bots very badass

**Comment by ermiyaeskandary** [comment]
@pomega Thanks - forgot the update the link - from the previous A\* bot, which is in a separate branch now as it was experimental...
