### ISSUE TITLE
Reduce food glow ?

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#236]
Reduce food glow when mobile rendering is on ? Should we implement it ?

**Comment by dracco1993** [comment]
Sure, why not?
I feel like that could help improve FPS.

**Comment by Seple** [comment]
not only mobile rendering only all the time :)

**Comment by dracco1993** [comment]
Yeah, I could totally see this as an option to allow all the time.

**Comment by ermiyaeskandary** [comment]
So all the time ?

**Comment by ermiyaeskandary** [comment]
I also personally think all the time as when you zoom out and in the flow is just annoying - not nice... Annoying...

**Comment by ChadSki** [comment]
Omg yes please! :+1:

Edit: All the time, definitely.

**Comment by ermiyaeskandary** [comment]
We could reduce glow but I was thinking about the slither.io mobile app. It seems really slimmed down, with no glow and ...

Maybe we could implement what the mobile app does or trick the server .. ??

**Comment by ChadSki** [comment]
There's a mobile app? I thought there was just a mobile website.

Probably not possible to copy the mobile app... It would be written in Obj-C if iOS or Java if Android, using totally different APIs.

The best approach is probably similar to how @tjorim monkeypatched the render code to avoid the slow zooming in. We just need to patch the part that draws food and eliminate the glowy part.

**Comment by tjorim** [comment]
Yes there is ~~(or was, looks like it isn't up anymore).~~
It uses Adobe Air and an Flash file.

Looks like it got some actionscript but can't view it.
![d24ead90c31bfc1af8bea8d6a8ace14d](https://cloud.githubusercontent.com/assets/1294876/15659657/840c905c-26ce-11e6-8553-69cea3f9e900.png)

**Comment by Salvationdk** [comment]
@tjorim i exported it and placed it here https://github.com/Salvationdk/slither_android

**Comment by Seple** [comment]
and please delete bright frame http://iv.pl/images/27283085376799063811.jpg <--- bright frame "strengthens" glow

**Comment by ermiyaeskandary** [comment]
@Seple Do you see a change in performance ? That's there for visual debugging purposes...

**Comment by Seple** [comment]
no difference

**Comment by ermiyaeskandary** [comment]
@Seple So we'll keep it ... 

> That's there for visual debugging purposes...

**Comment by ermiyaeskandary** [comment]
Anyone know of any scripts, mods or extensions which remove/reduce glow? If so, maybe I can port it...

**Comment by Seple** [comment]
Reduce food glow - When can I expect?

**Comment by Salvationdk** [comment]
for now the food can be scaled and colour changed.. but the glow is still loaded after the injection

**Comment by Seple** [comment]
Very nice please work

**Comment by ChadSki** [comment]
Fixed in #311.
