### ISSUE TITLE
toggle for disabling right-click functionality

### ISSUE THREAD

**Issue by jellybabies** [ermiyaeskandary/Slither.io-bot#238]
Invariably after playing an hour my hand can get a little cold in this not-ergonomic configuration and I can excited accidentally tap right click.  

I would like a UI key to disable right-click-bot-enable leaving only the letter 'T' for this.

I looked through the javascript myself trying to find which line(s) might be responsible but was unable to decipher it.

**Comment by Salvationdk** [comment]
I still use the right click option, and would be sad if this goes away..

**Comment by Drflash55** [comment]
I see there being too many toggles for things... If @ErmiyaEskandary want's to go through the trouble of making a toggle for this, then it's fine by me.

**Comment by ermiyaeskandary** [comment]
TBH, toggles for everything seems.... seems...

**Comment by marconia** [comment]
What would one need to change one's self to disable right-click bot toggle?

**Comment by ermiyaeskandary** [comment]
I don't agree with this suggestion, with all due respect...

**Comment by Seple** [comment]
@jellybabies Weak argument, sorry :-1: more advantages than disadvantages.

Options :
bot - the right mouse button disable / enable.
"Fast Boost" - the left mouse button disable / enable.

wtf? he doing himself the problem of human error is obvious...

**Comment by ChadSki** [comment]
You can disable the right-click by commenting out this whole case: https://github.com/ErmiyaEskandary/Slither.io-bot/blob/f2cc375d3aeb685f69efd91c4e8867c2eee47e7b/bot.user.js#L1117-L1119
