### ISSUE TITLE
Custom Hotkeys menu

### ISSUE THREAD

**Issue by Salvationdk** [ermiyaeskandary/Slither.io-bot#239]
Add an option to allow custom hotkey assign. Like input fields in a menu toggle, that would be saved in cfg #like the menu toggle for the adjustment angle in A*

**Comment by Drflash55** [comment]
So, you want to have a menu which will allow you to set your own hotkey for the functions on the bot...

@ErmiyaEskandary, does this sound good to you?

**Comment by marconia** [comment]
Maybe a wiki for changing the key assignments?

Maybe break into two userscripts?  One for changes the user wishes to retain despite updates..

**Comment by ChadSki** [comment]
Please do add a section to the wiki if you'd like to! https://github.com/ErmiyaEskandary/Slither.io-bot/wiki

The relevant code is here: https://github.com/ErmiyaEskandary/Slither.io-bot/blob/f2cc375d3aeb685f69efd91c4e8867c2eee47e7b/bot.user.js#L1020

**Comment by Salvationdk** [comment]
@Drflash55 precise

**Comment by ermiyaeskandary** [comment]
**Duplicate** of #219: 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> To report a bug start by: Searching for existing issue reports. No one wants to deal with duplicate reports.
