### ISSUE TITLE
Highscore Savings Issue with Changing Skin

### ISSUE THREAD

**Issue by Drflash55** [ermiyaeskandary/Slither.io-bot#243]
If you already played a game, and lost... If the bot is still on, you can go to change skin, and save, and the score will be submitted to the top 10 highscores. If you repeat this, it will keep adding a new score with the same amount of points, even though you didn't play the game...

Is this little issue able to be fixed? It's not major, but just a little minor bug with how the game records scores... Also, the hotkeys display overlaps the highscores...

![Why does this happen?](http://image.prntscr.com/image/e8531e5f171f41a8a429b20508662ef8.png)

**Comment by Seple** [comment]
Yes bug grafic :+1:  Please also menu margin - closer to the left side...  
...and I think that is sufficient enough top 3 ? <--- what do you think ?

Maybe readable menu layout? 
examplethe order in the queue...

T / Right Click Bot enabled/disabled
O   Mobile rendering 
<                 Mouse wheel   Zoom in/out
A / S   Collision radius multiplier 12/6
D ...... 5/25
I   Automatic Respawning
G ....
Y   Visual debugging
U   Log debugging
H   Hide overlays
<               Z   Reset zoom
Mouse wheel Zoom
Q   Quit to menu
<               ESC Quick respawn
TOP 3 - colored ?

and also does not remember settings: "radius multiplier" Bug Menu ;)

**Comment by Salvationdk** [comment]
i fixed the graphic bug in #256

**Comment by Salvationdk** [comment]
Its not really latest 10 games its top 10 list of the games totally played

**Comment by ermiyaeskandary** [comment]
Fixed with #256 !
