### ISSUE TITLE
Slither.io-bot A* V. 1.1.4 

### ISSUE THREAD

**Issue by VanishingTacos** [ermiyaeskandary/Slither.io-bot#244]
The background,all snakes, and all food are not there. Just a black screen with the normal HUD around it. Everything comes up when launching the site, but it goes to a black screen with the normal HUD when starting the game. This only started happening after the update to 1.1.4.

**Comment by Seple** [comment]
Please instal new version 1.2.2 https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/bot.user.js

**Comment by ermiyaeskandary** [comment]
@VanishingTacos if you want to use the A\* version, update your code with the code in A\* branch. If you want the lastest code for the bot, refer to @Seple 's link above. Hope that solved your problem ! :+1:
