### ISSUE TITLE
can you make lib 

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#245]
can you make a lib 😀

**Comment by ermiyaeskandary** [comment]
What do you mean ?

**Comment by ghost** [comment]
like can we use it like rattle snake and can you saw how to implement your features in my feeder bot

**Comment by ermiyaeskandary** [comment]
This is just a script which injects into the page...

**Comment by ghost** [comment]
so can we use this to make feeder bot

**Comment by ermiyaeskandary** [comment]
In a way, if that is your goal, there are way better projects out there for your purpose.

**Comment by ghost** [comment]
can you help or suggest some

**Comment by ermiyaeskandary** [comment]
https://github.com/dahquan/rattlesnake/blob/master/examples/feedme.js and more...

**Comment by ghost** [comment]
i used that but i want to include your features of avoiding others etc

**Comment by ghost** [comment]
eat food

**Comment by ermiyaeskandary** [comment]
Ah - so a feeder bots which avoids others ?

**Comment by ghost** [comment]
and eat pellets

**Comment by ghost** [comment]
yea right

**Comment by ermiyaeskandary** [comment]
Ah...

**Comment by ghost** [comment]
can you help me or tell how to do it

**Comment by ghost** [comment]
can you... tell me how to make it eat food atleast

**Comment by ermiyaeskandary** [comment]
I neither condemn or condone feeder bots but it is up to you to use the code together or make it work so it is a feeder bot.

**Comment by ghost** [comment]
ok

**Comment by ermiyaeskandary** [comment]
:+1: - no offense intended BTW

**Comment by ghost** [comment]
ok
