### ISSUE TITLE
Question about canvas

### ISSUE THREAD

**Issue by clemens-tolboom** [ermiyaeskandary/Slither.io-bot#248]
- [x] What is this canvas for? Guess it's more a canvasUtil right? Renaming in #253
- [x] What is the real Canvas? Guess it is the screen visible area?
- [x] What is the Map? See https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/docs/conversion_algorithms.rst

Could we document this? And maybe rename canvas into canvasUtil?

``` javascript
 var canvas = window.canvas = (function () {
     return {
...

        // Convert map coordinates to mouse coordinates.
        mapToMouse: function (point) {
```

**Comment by ChadSki** [comment]
Good point that the name is confusing. It's just a module name.

At first it was only:

```
var canvas = (function () {
    return {
```

Which worked, but the canvas module was not visible from the javascript console in the browser, so we also attached it to `window`, where all our global variables go.

Canvases are used a lot in HTML5 so I definitely agree `canvas` is confusing as-is. The name `canvasUtil` is okay with me, what do others think?

**Comment by ermiyaeskandary** [comment]
Yep! - I agree :+1:

**Comment by clemens-tolboom** [comment]
I've updated the summary.

Question remaining is _what is the map?_

**Comment by Drflash55** [comment]
> Question remaining is "What is the map?"

I have no idea what that even means...

**Comment by ermiyaeskandary** [comment]
@clemens-tolboom The map is the the game area - restricted by the game walls. The canvas is what we can draw on - where everything is rendered. The **canvas module** in the code is the module we use for updating the stats, visual debugging and so forth - the visual stuff. Hope that made it clear and sorry for the late reply. :+1:

**Comment by clemens-tolboom** [comment]
Thanks for the prompt reply :p

So the map == game area or how I call it the arena. Is that worth a PR
- change map to arena
  OR
- document map is the game area

What bothers me about documentation is why is it in another branch. That doesn't make sense to me. It should be in the branch the developers / contributors work in. Unless it's a github pages website of course :-)

**Comment by clemens-tolboom** [comment]
He ... map is explained in https://github.com/ErmiyaEskandary/Slither.io-bot/blob/master/docs/conversion_algorithms.rst sort of. Will read that soon :-)

Closing
