### ISSUE TITLE
can you give eat food code

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#252]
can you give eat food code if i press e

**Comment by ermiyaeskandary** [comment]
It isn't just a specific section. All the different parts in the code go hand in hand which results in the bot you see now.

**Comment by ravyn120** [comment]
@kurama129 it's simple just find the packet for food if it has a packet I haven't checked and make a option for it like 33 = food then set in the userscript to emit a button to a socket.io server and make the feeder do that function

**Comment by ravyn120** [comment]
@kurama129 if I have the time I'll make it for your slither bots or whatever

**Comment by Drflash55** [comment]
I'm having a hard time understanding what @ravyn120 is trying to say...

Is he talking about a key that will emit food in front of the snake? That sounds totally bizarre...

**Comment by ghost** [comment]
i dont need it i implemented ermiya slither bot in my every bot all i need is reconnect option

**Comment by ermiyaeskandary** [comment]
@kurama129 What reconnect option? By the way, if you are using our code, you are obliged to share it under the MPL. :+1: Stick it into a repo and share the link so we can understand what you want ...

**Comment by ravyn120** [comment]
@Drflash55 no I'm talking about a slither.io client I'm talking about defining the packets

**Comment by ChadSki** [comment]
You may be interested in this: https://github.com/ClitherProject/Slither.io-Protocol/blob/master/Protocol.md
