### ISSUE TITLE
How do i use .eslintrc

### ISSUE THREAD

**Issue by pllsner** [ermiyaeskandary/Slither.io-bot#261]
I am using srware iron browser. how do i use the  .eslintrc file with tampermonkey. a short tutorial for us es5 script users would be greatly appreciated. I tried installing eslint with npm.  seems nothing worked. now i am at a standstill. what am i doing wrong?

**Comment by ermiyaeskandary** [comment]
Just follow the text tutorial or the website tutorial....
It should set you up and running...

**Comment by pllsner** [comment]
thank you for the quick reply. i will reread the info there,and try again. :)

**Comment by ermiyaeskandary** [comment]
@pllsner ...

**Comment by ermiyaeskandary** [comment]
Closed - if any problems still occur, please comment again...
