### ISSUE TITLE
Remove laggy logo animation ?

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#263]
How about removing the laggy slither.io logo animation ?

**Comment by ermiyaeskandary** [comment]
If you want to test it out, it's in the `removelaggylogoanimation` branch - https://github.com/ErmiyaEskandary/Slither.io-bot/raw/removelaggylogoanimation/bot.user.js

**Comment by Drflash55** [comment]
The logo animation causes lag?

:confused:

**Comment by ermiyaeskandary** [comment]
@Drflash55 No it doesn't - it's laggy itself .... Useless anyway IMO

**Comment by Drflash55** [comment]
@ErmiyaEskandary Oh, okay...

**Comment by ermiyaeskandary** [comment]
@Drflash55 Only the animation is removed- the actual logo is still there... **Faster page loading time is the major difference.** You can test it ^^^

**Comment by Drflash55** [comment]
@ErmiyaEskandary Alrighty, hold on a few moments while I test it...

**Comment by Drflash55** [comment]
Loading times are increased much quicker, and the page doesn't have to load anything else except the logo, since my school firewall doesn't allow access to the servers.

It's almost instantaneous, which is incredible.

**Comment by ermiyaeskandary** [comment]
@Drflash55 So approved ? :smiley:

**Comment by Drflash55** [comment]
@ErmiyaEskandary Sure thing... It works like a charm. :+1:

**Comment by ermiyaeskandary** [comment]
Merged - keeping issue open for the time being to see other people's views as well 
@Drflash55 Thanks again for testing :+1:

**Comment by Drflash55** [comment]
@ErmiyaEskandary You're welcome!

**Comment by Defimatt** [comment]
:+1: I can't believe how much difference this makes to loading speed

**Comment by ermiyaeskandary** [comment]
That's enough approvals - closing... ;)
