### ISSUE TITLE
pressing key options don't work

### ISSUE THREAD

**Issue by iamlikeyou** [ermiyaeskandary/Slither.io-bot#277]
Hi, the options by pressing a key wont work, they used too, but now they don't

A/S/D/G/Y/U/H/Z/T Doesn't work

i: zooms in?
O: zooms out?
ESC/Q/W: Work

Browser: Chrome (Latest)
OS: Mac (Latest)

**Comment by ermiyaeskandary** [comment]
What version ?

**Comment by ermiyaeskandary** [comment]
Can you toggle the bot ?

**Comment by Defimatt** [comment]
Tested 1.2.6 Chrome OS X, can't reproduce.

**Comment by ermiyaeskandary** [comment]
Same here 1.2.6 Chrome and Firefox Linux, can't reproduce

**Comment by ChadSki** [comment]
Sounds like #126

**Comment by ermiyaeskandary** [comment]
I can't reproduce this - @iamlikeyou can you provide what version of the script you are running ?

**Comment by ermiyaeskandary** [comment]
2 days - no response and no confirmation.
Closing....
If confirmed by a contributor that this is a valid bug, please comment and reopen.

**Comment by iamlikeyou** [comment]
it was "Slither.io Mods v3.3" from Slitherio.org, that was conflicting with the bot script keys

**Comment by ermiyaeskandary** [comment]
Yeah that's why
