### ISSUE TITLE
shift headCircle to front instead of increasing for running snake

### ISSUE THREAD

**Issue by alexzeit** [ermiyaeskandary/Slither.io-bot#280]
The increasing of the headCircle if the snake is running is not the best thing, it is like you start to drive your car faster and try to look further in all directions. No snakes from back can overcome you, that is why I think it is better to shift the circle to front instead to increase it.

**Comment by alexzeit** [comment]
Other possibility to use an additional circle in the front of the snake if it runs

**Comment by ChadSki** [comment]
Why don't you try it out and see if it works better?

Pop in the gitter chat if you need help navigating the codebase.

**Comment by ermiyaeskandary** [comment]
Documentations is not fully done yet but it may help you in some cases as well. But the Gitter chat is the way to go !

**Comment by alexzeit** [comment]
i have tried it, it works better
just an example: you have a snake body on the left side close to the blue circle , and your snake has found some amount of food in front and starts to accelerate, what will happen? The blue circle will increase and an collision will be registred to the left that was not seen before just because the circle is increased. but this is not that should prevent the snake moving, it is on the left and your snake just goes ahead

**Comment by ermiyaeskandary** [comment]
@alexzeit If it does, make a PR! Great! And we'll be happy to take a look at it.
But please meet all requirements and read the guidelines and the contributing section in the README !

**Comment by Seple** [comment]
Manual control - buton mouse without a growth circle. 
Possible?

**Comment by alexzeit** [comment]
Sorry, if you like, you can easily implement it, I'll do the changes in predator-bot branch that is not fit to your project.

**Comment by ermiyaeskandary** [comment]
@alexzeit Sorry as well then. If you want to contribute and help, then make a PR. If not, then it's your choice. :+1:
