### ISSUE TITLE
Go for preys only over a set length

### ISSUE THREAD

**Issue by tjbcg** [ermiyaeskandary/Slither.io-bot#29]
The bot should not try to hunt preys without enough length. So I suggest setting a minimum length of about 200.

**Comment by K00sKlust** [comment]
it does already, but with a minimum of 20.. But it should start hunt at 200, and stop at, for example 100. If we would change the 20 to 200, it would hunt at 201 and stop if it gets under 200..

**Comment by tjbcg** [comment]
@K00sKlust So can we have to change 20 to 100 in the first place ? Or would that cause issues ? I haven't read the code yet

**Comment by K00sKlust** [comment]
It doesn't cause issues, but it also doesn't improve the bot. We should implement a check (can the bot make it if it's boosting?).

**Comment by ermiyaeskandary** [comment]
But how would we calculate how much length we need unless we put a tried and guaranteed set value in ?

**Comment by ermiyaeskandary** [comment]
But it shouldn't go below 200 or any other number if it gets the prey before it gets decreased to that value. So we need a set value which guarantees the capture of the prey.

**Comment by tjbcg** [comment]
The thing is I think we should detect only preys that are near, because else the bot will just loose more than what the prey will give. And if that gets implemented, then we can safely assume 200 is enough

**Comment by ermiyaeskandary** [comment]
Can we do sortedPrey.distance ? Do your distance functions let me do that ?

**Comment by tjbcg** [comment]
@ErmiyaEskandary Yep, sortedPrey[index].distance

**Comment by ermiyaeskandary** [comment]
Ah OK - lemme test something
