### ISSUE TITLE
Does quick respawning leave food behind?

### ISSUE THREAD

**Issue by xPhillipx** [ermiyaeskandary/Slither.io-bot#293]
Does quick respawning leave food behind?

**Comment by ermiyaeskandary** [comment]
What do you mean?

**Comment by ChadSki** [comment]
I'm not sure... Maybe your abandoned snake just starts going in a straight line? I've never seen another snake disappear...

**Comment by ermiyaeskandary** [comment]
Oh - I always though it just goes puff and evaporates but I haven't seen other snakes just dissapear...

**Comment by ermiyaeskandary** [comment]
We can maybe test it it out using zoom and the movetoxy in @clemens-tolboom PR ? Zoom out to see what happens ?

**Comment by phrokton** [comment]
I have seen other snakes disappear, but usually indirectly while I was following them, or knowing their speed move towards their location after killing something else.  Poof gone, no carcass.

When I need to do something else and want to benefit no one I find an abandoned wall section to disappear myself.

**Comment by ChadSki** [comment]
@phrokton have you ever seen they disappear other than crashing into a wall?

**Comment by xPhillipx** [comment]
I have seen other snakes disappear without a trace.

**Comment by ChadSki** [comment]
Sounds like the mystery has been solved!
