### ISSUE TITLE
Wiki error "How to override the game's javascript"

### ISSUE THREAD

**Issue by pllsner** [ermiyaeskandary/Slither.io-bot#299]
I tested out this extension by hard-coding acceleration to always be enabled. Test was a success -- Left mouse clicks did not cause any speed change (always accelerated).
 Should read.........
I tested out this extension by hard-coding acceleration to always be **disabled**. Test was a success -- Left mouse clicks did not cause any speed change (**never** accelerated).

**Comment by ermiyaeskandary** [comment]
Huh ?

**Comment by pllsner** [comment]
the value 2 disabled any acceleration of worm in my test. This wiki is reporting wrong results from the code change.

**Comment by ermiyaeskandary** [comment]
What page of the wiki ?

**Comment by pllsner** [comment]
[https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/How-to-override-the-game's-javascript]

**Comment by pllsner** [comment]
reinstalled resource override.  reran the test.  a value of 2 disables any acceleration. Left mouse click does not accelerate.

**Comment by ChadSki** [comment]
@pllsner weren't you the one who got that working on the first place?

I copy+pasted that wiki page from your issue #274

**Comment by ChadSki** [comment]
Oh you mean the wiki is incorrect. Why don't you edit the wiki to be correct then? I thought I was clarifying things but probably got it wrong.

**Comment by pllsner** [comment]
#274 states a value of 2 disables acceleration. Not a big deal, i just wanted to get the info correct.
i was not aware I could edit the wiki, or i would have. :)

**Comment by ChadSki** [comment]
So in your test, 2 was the same as 1? Or was 2 the same as 0?

2 is an odd number to use anyway, since it's not normally a valid value.

If you had set acceleration to 1, then it would always be enabled, right?

**Comment by pllsner** [comment]
2 was the same as 0. The logic in the function became false.
original:  function setAcceleration(b) {  null != snake && (snake.wmd = 1 == b)} 
altered:  function setAcceleration(b) {  null != snake && (snake.wmd = **2** == b)}
Given that b = 1 or 0, (the only values passed to this function)
the table below explains the comparison operator  == :
original function:
Operator..................Description...............Comparing............or.........Returns 
 ....==.........................equal to.....................1 == b.............1 == 0.......false
 ..........................................................................................1 == 1........true
altered function:
Operator..................Description...............Comparing............or.........Returns 
 ....==.........................equal to.....................2 == b.............2 == 0.......false
 ..........................................................................................2 == 1.......false
by calling this altered function with setAcceleration(0), or setAcceleration(1), the condition is always false, so no acceleration ever occurs.
.....update .     modifying the function appears to disable any acceleration.

**Comment by ChadSki** [comment]
Oh, I see. :+1: Well feel free to edit this wiki and close the issue when fixed.

**Comment by ChadSki** [comment]
Oops wrong button lol.
