### ISSUE TITLE
Automatically replay after death

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#3]
Bot can use `connect()` function to rejoin the game after a death.
TODO: Add this functionality.

**Comment by Evanito** [comment]
Okay I'm (mostly) done with this feature.
Just ironing out some bugs.

**Comment by ermiyaeskandary** [comment]
It doesn't rejoin for me. Can people confirm ?

**Comment by Evanito** [comment]
Bot needs to be enabled (check if it is using f12 console) and will attempt to rejoin every 10 seconds. This should be enough time to join.

Since the feature is added, I'm closing this.

**Comment by Seple** [comment]
I renew topic
