### ISSUE TITLE
slow motion!

### ISSUE THREAD

**Issue by vectorserver** [ermiyaeskandary/Slither.io-bot#300]
Возможно ли сделать замедление времени?

Is it possible to make the time dilation ?

http://www.html5rocks.com/en/tutorials/canvas/performance/

**Comment by ermiyaeskandary** [comment]
So make the game go slow?

**Comment by vectorserver** [comment]
Yes

**Comment by ermiyaeskandary** [comment]
Why?
And even if it was possible, we are making an AI bot here - not trying to mod the game...

**Comment by ChadSki** [comment]
Out of scope for the bot, I think. But an interesting idea!

Hope you stick around :)
