### ISSUE TITLE
does not circle

### ISSUE THREAD

**Issue by grewa** [ermiyaeskandary/Slither.io-bot#327]
please fix code <3

**Comment by K00sKlust** [comment]
Please look at this https://github.com/ErmiyaEskandary/Slither.io-bot/issues/326#issuecomment-247601759 comments. The project is dead, developers lost interest. If you got coding experience, you could try fixing it yourself.

**Comment by ermiyaeskandary** [comment]
@K00sKlust @grewa Sure! Please also readme, we have fortunately IMO lost interest as now we can progress onto other projects. But yes, project has been discontinued but further development is not to be discouraged.

Life is busy for all of us, isn't it? :)
