### ISSUE TITLE
Setting for focus on moving food (prey)

### ISSUE THREAD

**Issue by kakol20** [ermiyaeskandary/Slither.io-bot#37]
Very annoying and stupid feature
Even when i enable(disable?) the bot, it's still on boost mode

just remove it. there's no point to it.

**Comment by haylinmoore** [comment]
Yes it focuses way to much. +1 for remove

**Comment by Evanito** [comment]
A toggle to disable this feature will be added

**Comment by ghost** [comment]
well personally think that this freature is great maybe you can make it go after moving food that is half as far as it is right now then it would not have to wastle that much boosts

**Comment by Evanito** [comment]
Fixed
