### ISSUE TITLE
Add highscores from last (10) games

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#38]
- [ ] Use `sessionStorage` or`localStorage` to keep a high score list for previous lives of the bot.
- [ ] Show leaderboard visually on screen

**Comment by dracco1993** [comment]
Are we talking about the last 10 scores we had when we died?
That's what makes the most sense to me.

**Comment by Evanito** [comment]
Yes. Perhaps we could also sort the best scores too and say how many lives ago each was.

**Comment by ermiyaeskandary** [comment]
Where would the leaderboard be displayed on the screen ?

**Comment by ermiyaeskandary** [comment]
We could do a best score .... But a leaderboard visually on the screen for our scores is overkill...

**Comment by ermiyaeskandary** [comment]
If people agree, we could do a best score overlay... I could do that easily once I find out how the score is calculated...

**Comment by ChadSki** [comment]
I'd like to know my _own_ best score, at least.

**Comment by chancity** [comment]
Is t your score just your length?

**Comment by ChadSki** [comment]
Yes it is.

I mean instead of just seeing that "starlord" or whoever managed to reach 200k, I'd like to know that my personal best is 40k or whatever.

**Comment by Seple** [comment]
How function intensely CPU?

**Comment by ermiyaeskandary** [comment]
@ChadSki That's what I meant - our own personal best score...

**Comment by ermiyaeskandary** [comment]
@Seple Really simple. Just checking variables and then changing the overlay.

**Comment by Drflash55** [comment]
There should be an option in the menu that allows you to pick whether or not you want to see the last 10 highscores...

**Comment by ermiyaeskandary** [comment]
> But a leaderboard visually on the screen for our scores is overkill...

**Comment by ermiyaeskandary** [comment]
Done with latest system change...

**Comment by tjorim** [comment]
Maybe we could still preserve a personal highscore in localStorage?

**Comment by ermiyaeskandary** [comment]
Ah - so in addition to the average score ?

**Comment by tjorim** [comment]
Is the average score kept between sessions?

**Comment by ermiyaeskandary** [comment]
Lemme check...

**Comment by ermiyaeskandary** [comment]
No : 

``` javascript
updateStats: function() {
            var oContent = [];

            if (bot.scores.length === 0) return;

            oContent.push('games played: ' + bot.scores.length);
            oContent.push('avg score: ' + Math.round(
                bot.scores.reduce(function(a, b) { return a + b; }) / (bot.scores.length)));

            for (var i = 0; i < bot.scores.length && i < 10; i++) {
                oContent.push(i + 1 + '. ' + bot.scores[i]);
            }

            userInterface.overlays.statsOverlay.innerHTML = oContent.join('<br/>');
        },
```
