### ISSUE TITLE
Check FPS and auto change graphics

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#40]
- [x] Add FPS check every several seconds.
- [x] When below ~20, switch to low graphics settings on the fly and disable unneeded features. Maybe slow down the bot clock a few milliseconds.
- [x] When above ~40, switch back (gap is needed between the two triggers so it doesn't turn on and off madly.) Or maybe have multiple intermediate graphics levels.
- [x] Be able to toggle this function.

**Comment by Evanito** [comment]
Needs #50

**Comment by ermiyaeskandary** [comment]
FPS can be checked using the current function ?! @K00sKlust

**Comment by K00sKlust** [comment]
yes. `window.framesPerSecond.getFPS()`. I also added a filter, so it smoothes.

**Comment by K00sKlust** [comment]
i mean, to avoid strange peaks in the fps.

**Comment by ermiyaeskandary** [comment]
Can people test if the latest commit works ?

**Comment by ermiyaeskandary** [comment]
Below 20 it should switch

**Comment by Seple** [comment]
all the time auto switch (- flashes image)

**Comment by ermiyaeskandary** [comment]
What do you mean ? Does it switch even when it is above 20 or only when it is close to 20 ?

**Comment by Seple** [comment]
Auto regardless switch picture - only flashes image

**Comment by ermiyaeskandary** [comment]
??
Post an image - it helps.

**Comment by ermiyaeskandary** [comment]
Is circle time defence mode ?

**Comment by Seple** [comment]
> Is circle time defence mode ?

no no

> What do you mean ? Does it switch even when it is above 20 or only when it is close to 20 ?

Yes

has been dropped fps was better
I had (it was) 49-51 FPS 
(off bot - disable - up 50 FPS)
http://s32.postimg.org/qhoidfqth/no_bot_disable.jpg
(on bot - enabled) I now have (Now is) 12-20 FPS
http://s32.postimg.org/x26tcvo3p/dfdfdfdf.png
down FPS :(

and to constantly jumps and turns the image (- flashes image - switch rotation pulse image)

# Please no auto, better manualy....

Please optimize all of the code for the bot, so it's less-intensive on the CPU and gives decent FPS.

**Comment by ermiyaeskandary** [comment]
@FliiFe above :( (_in doubt_)

**Comment by ermiyaeskandary** [comment]
@seple I'll change it soon.

**Comment by Seple** [comment]
I renew my request. Please option no auto, better manualy.

**Comment by ermiyaeskandary** [comment]
This is a good feature. I'm just working on something else ATM.

**Comment by Seple** [comment]
Why this graphics solution for me (chrome) works much better? no Lag FPS. Without inheritance and swimming FPS.
https://greasyfork.org/pl/scripts/19416-slither-io-slithere-com-v3-0
- Menu >>> Option Graphic Quality >>> Optimizer

**Comment by ChadSki** [comment]
I'm not sure. "Optimized" graphics quality seems to just set `renderMode = 2`. Probably that script just does not add too much CPU-heavy processing.

Do you mean that using our script AND that script together fixes the lag?

I can also see why automatically switching to mobile rendering could be annoying....

**Comment by Seple** [comment]
> Do you mean that using our script AND that script together fixes the lag?

Yes. Together script and script = no Lag FPS

> I can also see why automatically switching to mobile rendering could be annoying....

Automatically constantly switch from mode normal/mobile and jump fps
- See the photos switches fall before mode change mobile fps http://s32.postimg.org/x26tcvo3p/dfdfdfdf.png 
  drop fps is not constant. 
- Before this change had fixed. I had (it was) it was like that: http://s32.postimg.org/qhoidfqth/no_bot_disable.jpg (photo bot disabled)

**Comment by Seple** [comment]
> I can also see why automatically switching to mobile rendering could be annoying....

Automatically constantly switch from mode and jump fps

**Comment by ermiyaeskandary** [comment]
So should I remove it all together ? Add your reaction ...

**Comment by ermiyaeskandary** [comment]
> Please option no auto, better manualy.
> 
> I can also see why automatically switching to mobile rendering could be annoying....

**Comment by Seple** [comment]
helpless

**Comment by ermiyaeskandary** [comment]
@Seple says no. What about you @ChadSki @K00sKlust ?

**Comment by Evanito** [comment]
@ErmiyaEskandary How about we dont switch to mobile rendering automatically, and instead we add features so if your fps is high, we use stuff like the expensive distance check and rendermode 3. But if you are low fps its rendermode 2 and the inexpensive distance.

And be able to toggle this feature

**Comment by ermiyaeskandary** [comment]
The render modes would be mobile rendering and the other things would be useless IMO, no offense.

**Comment by Seple** [comment]
I have no option `renderMode = 2` who became good enough for my computer core2quad q9400 and ati radeon 6670 ddr5, windows, chrome. 
Please option no auto, better manualy.

Auto mobile rendering - maybe good
but why jumping declines swimming
why swimming, jumping fps? not stable fps 
especially when many snakes on the map

**Comment by ermiyaeskandary** [comment]
@Evanito So should I remove it ? I need more confirmations to remove it..

**Comment by ermiyaeskandary** [comment]
Lower FPS confirmed... Not really useful ATM and has more cons than pros ... Removing
