### ISSUE TITLE
Make visual debug target prey when hunting

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#49]
Instead of pointing at food, have the visual line lead to the Prey it is chasing.

**Comment by ermiyaeskandary** [comment]
@FliiFe as you are familiar with visual debugging ?

**Comment by dracco1993** [comment]
I'm going to suggest that we build additional functionality in here, or increase the scope slightly.
I feel like it would be really helpful to have 2 lines for visually debugging:
1) Dot/line to where we currently have the mouse
2) Dot/line to some arbitrary target

As of right now, this would be the same thing.
This would allow us to, in the future, "target" an area behind something, another snake for example, but at the same time still keep the mouse input location for actually going around the obstacle.

**Comment by K00sKlust** [comment]
Is already fixed because of using goalCoordinates.
