### ISSUE TITLE
 [Suggestions] Two mouse buttons - disable/enable bot - "Fast Boost"

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#54]
Hello
1. Please restore the auto startup play game.
2. Replace or add options: "Defense mode - bot turns around in a perfect circle" 
   do not turn in a perfect circle always head protrudes - better add "auto distance" from others (and prevents collisions).
3. To facilitate enable fast switching bot disable / enable the right mouse button - not key "T" (replace - key / button).
4. "Fast Boost" - Always possible under the left mouse button (independently / regardless - bot enabled).
5. Save / Remember selected skin + options.

I'm sorry for my language english is not good. Thank you in advance if possible to change the.
Thank you for your work. Regards. GL&HF ;)

**Comment by ermiyaeskandary** [comment]
> better add "auto distance" from others (and prevents collisions).

Enemy avoidance being worked on

> Please restore the auto startup play game.

Not possible for a reason I can't remember @Evanito ?

> bot turns around in a perfect circle" do not turn in a perfect circle always head protrudes

Sorry - mistake. Changing...

> To facilitate enable fast switching bot disable / enable the right mouse button - not key "Y" (replace - key / button).

Who agrees ? Thumbs up or thumbs down

> Save / Remember selected skin + options.

Options are remembered. "Remember selected skin" - @Evanito @FliiFe ?

> "Fast Boost" - Always possible under the left mouse button (independently / regardless - bot enabled).

You can boost using space regardless of if the bot is enabled or not. Is this what you mean or did I understand you wrong ?

**Comment by tjbcg** [comment]
> To facilitate enable fast switching bot disable / enable the right mouse button - not key "Y" (replace - key / button).

We can use both. Also, the current key is "T", not "Y".

> Save / Remember selected skin + options.

Selected skin is saved for me. Can you confirm @ErmiyaEskandary @Evanito ? Options are also saved using localStorage

**Comment by ermiyaeskandary** [comment]
> Selected skin is saved for me. Can you confirm @ErmiyaEskandary @Evanito ?

I can check soon but not right now :(

**Comment by ermiyaeskandary** [comment]
> To facilitate enable fast switching bot disable / enable the right mouse button - not key "Y" (replace - key / button).
> We can use both.

@FliiFe Do you think it would be good to use both ? Doesn't make a difference for me :|

**Comment by Seple** [comment]
> Selected skin is saved for me. Can you confirm @ErmiyaEskandary @Evanito ?
> I can check soon but not right now :(

Already know does not remember additional "non standard" skin Plugin: slither.io Slithere.com v2.9.2.

> Also, the current key is "T", not "Y".

Yes. I am sorry my mistake spell.

> Please restore the auto startup play game.
> Not possible for a reason I can't remember @Evanito ?

I am waiting for a response may however possible to quickly return to the game?

> To facilitate enable fast switching bot disable / enable the right mouse button - not key "T" (replace - key / button).
> We can use both.
> @FliiFe Do you think it would be good to use both ? Doesn't make a difference for me :|

Faster reaction response and switching when (enable / disable - bot button mouse and control mouse non bot - if do not bot) the right button on the mouse - orginal the game is the mouse. Would be nice ;)

**Comment by Seple** [comment]
(Point 2) ....

> bot turns around in a perfect circle" do not turn in a perfect circle always head protrudes 

This option is good if you want to lure us to surround Circle and of surprise and quickly jump on the " Quick Boost" before him

> "Fast Boost" - Always possible under the left mouse button (independently / regardless - bot enabled).
> You can boost using space regardless of if the bot is enabled or not. Is this what you mean or did I understand you wrong ?

When turned on the bot does not work manual option: "Fast Boost". 
Please add option on left mouse button.

Thank you for your attention and help. 
Regards;)

**Comment by tjbcg** [comment]
@Seple I think I misunderstood your request.

>  orginal the game is the mouse

Original game doesn't have a bot...

**Comment by Seple** [comment]
@FliiFe Naturally, I just want to help improve rapid reaction ;)

**Comment by tjbcg** [comment]
@Seple Can you explain clearly what is your request ? I know it is about rapid reaction, but what is it concretely ? I'm confused :confused:

**Comment by Seple** [comment]
in other words: "bot will help but not replace human thinking..."

**Comment by tjbcg** [comment]
@Seple But what is your request ? Is changing the enable/disable key what you want ?

**Comment by ermiyaeskandary** [comment]
> When turned on the bot does not work manual option: "Fast Boost". 
> Please add option on left mouse button.

Are you saying space doesn't work when the bot is on ?

**Comment by Seple** [comment]
I make two moves at once to set the direction and executes the commands such cases fast reaction every millisecond counts... 
I can not exactly explain Sorry :/

**Comment by ermiyaeskandary** [comment]
@FliiFe What @Seple is saying is that clicking the left mouse button is quicker than clicking T

**Comment by ermiyaeskandary** [comment]
@Seple Is that what you are saying ? Your request is to add in the right mouse button as a toggle for enabling/disabling the bot ?

**Comment by ermiyaeskandary** [comment]
> To facilitate enable fast switching bot disable / enable the right mouse button

**Comment by Seple** [comment]
> @FliiFe What @Seple is saying is that clicking the left mouse button is quicker than clicking T
> 
> @Seple Is that what you are saying ? Your request is to add in the left mouse button as a toggle for enabling/disabling the bot ?

Yes ;)

To facilitate enable fast switching bot disable / enable the right mouse button

YES YES YES :D

**Comment by ermiyaeskandary** [comment]
Right mouse button as the left mouse button is used for "Fast Boost" if that's how you want to put it

**Comment by ermiyaeskandary** [comment]
So you want us to add in the right mouse button as a extra toggle for the bot ? Is that your only request?

> When turned on the bot does not work manual option: "Fast Boost". 

Space is fast boost - it doesn't work when the bot is on ?

**Comment by K00sKlust** [comment]
It doesn't because of `window.setAcceleration();`

**Comment by Seple** [comment]
Please two mouse buttons;
- disable / enable bot - the right mouse button.
- "Fast Boost"            - the left mouse button.

**Comment by ermiyaeskandary** [comment]
@Seple When the bot is off, holding down the left mouse button or pressing space activates boost

**Comment by ermiyaeskandary** [comment]
As for this :

> disable / enable - the right mouse button

I'll work on it now

**Comment by Seple** [comment]
> @Seple When the bot is off, holding down the left mouse button or pressing space activates boost 

do not work
- bot ON "speed - Boost" does not work :(

**Comment by ermiyaeskandary** [comment]
@Seple OK.

**Comment by ermiyaeskandary** [comment]
I'm working on it now

**Comment by Seple** [comment]
OK Thank you!!! and Thank you for understanding my lame English :)

Your are doing a great job of beer for you :D 
Regards. GL&HF ;)

**Comment by ermiyaeskandary** [comment]
:+1:

**Comment by Seple** [comment]
When can i expect ?

**Comment by ermiyaeskandary** [comment]
@K00sKlust @FliiFe @Evanito @chancity Why doesn't this work for right click bot toggle ?

```
document.oldMouseDown =  document.onmousedown;
document.onmousedown = function(e) {
    document.oldMouseDown(e);
    e = e || window.event;
    // "Right click" to toggle bot in addition to the letter "T"
    if (e.which == 3){
        if (window.isBotRunning) {
            window.stopBot();
            window.isBotEnabled = false;
        } else {
            window.launchBot(5);
            window.isBotEnabled = true;
        }
    }

};
```

**Comment by tjorim** [comment]
@ErmiyaEskandary Actually it does work for me with a minor adjustment.
I changed the document. to window. as following:

``` javascript
// Save the original slither.io onmousedown function so we can re enable it back later,
// although we probably wouldn't need it.
window.oldMouseDown =  window.onmousedown;
window.onmousedown = function(e) {
    window.oldMouseDown(e);
```

We also might have to check 'e.button == 2' for Opera and ~~IE~~ (scratch that, there is no tamper-/greasemonkey for IE).

**Comment by ermiyaeskandary** [comment]
@tjorim Ah - that's what I needed. I'll see if I can check for Opera as well. 
Cheers :+1:

**Comment by tjorim** [comment]
@ErmiyaEskandary I changed the code a bit and had a first attempt at manually enabling acceleration.
It's working now ~~when the bot is disabled but when the bot is on, it's only accelarating for not even a second. I should probably check somewhere else in the code if something is disabling it again.~~

``` javascript
// Save the original slither.io onmousedown function so we can re enable it back later
window.oldMouseDown =  window.onmousedown;
window.onmousedown = function(e) {
    window.oldMouseDown(e);
    e = e || window.event;
    switch (e.which) {
        // "Left click" to manually speed up the slither
        case 1:
            if (window.playing) {
                window.setAcceleration(1);
                window.log('Manual boost...');
            }
            break;
        // "Right click" to toggle bot in addition to the letter "T"
        case 3:
            if (window.isBotRunning) {
                window.stopBot();
                window.isBotEnabled = false;
            } else {
                window.launchBot(5);
                window.isBotEnabled = true;
            }
            break;
    }
};
```

I think for Opera it is best to check both, but someone should first verify if it is needed.

Edit : crossed out a line ~ ErmiyaEskandary

**Comment by ermiyaeskandary** [comment]
@tjorim ~~Why do we want to disable manual speed ?~~ BTW, we can't check "e.which" for Opera. I'll commit soon.

**Comment by ermiyaeskandary** [comment]
@tjorim Do you have Opera ? Also, check your email. I invited you to Gitter :)

**Comment by tjorim** [comment]
I thought it was needed so (when controlling the slither manually) it only accelerates when the left mouse button is pressed. But it looks like it automatically stops when the button is released, my bad :)

**Comment by ermiyaeskandary** [comment]
@tjorim :+1:

**Comment by ermiyaeskandary** [comment]
This should work on it's own :

``` javascript
// Save the original slither.io onmousedown function so we can re enable it back later
window.oldMouseDown =  window.onmousedown;
window.onmousedown = function(e) {
    window.oldMouseDown(e);
    e = e || window.event;
    switch (e.which) {
        // "Left click" to manually speed up the slither
        case 1:
            window.setAcceleration(1);
            window.log('Enabling manual speed...');
            break;
        // "Right click" to toggle bot in addition to the letter "T"
        case 3:
            if (window.isBotRunning) {
                window.stopBot();
                window.isBotEnabled = false;
            } else {
                window.launchBot(5);
                window.isBotEnabled = true;
            }
            break;
    }
};
```

**Comment by ermiyaeskandary** [comment]
@tjorim Do you have Opera ?

**Comment by tjorim** [comment]
Yes indeed, I just updated my previous code.
Maybe we should check if the game is actually playing before enabling the acceleration.

I haven't installed Opera currently, I will install it and check my email in a minute.
Question: do you mind to type ` ```javascript` before your code to enable syntax highlighting? Thanks in advance.

**Comment by ermiyaeskandary** [comment]
@tjorim Sure - syntax highlighting done. 
To check if the game is running we can do 

``` javascript
if (window.playing) {}
```

**Comment by ermiyaeskandary** [comment]
Does manual acceleration work when the bot is off ?

**Comment by ermiyaeskandary** [comment]
If it does, then we can also check if the bot is running or not :

``` javascript
if (window.playing && window.isBotRunning) {}
```

**Comment by ermiyaeskandary** [comment]
I'm testing to see if Opera works as it should do with `e.which`

**Comment by Seple** [comment]
Thank you very much <3
