### ISSUE TITLE
Defence button is not "[" as is shown in the overlay.

### ISSUE THREAD

**Issue by stere0123** [ermiyaeskandary/Slither.io-bot#55]
In the README and the script itself, defence mode is indicated as being triggered by "D", but the in-game overlay says "[" triggers it, which is not true.

See: http://i.imgur.com/6vQq7Gs.png and http://i.imgur.com/x7Zg8Ix.png

**Comment by ermiyaeskandary** [comment]
Is this the latest version ?

**Comment by stere0123** [comment]
This would be whatever version tampermonkey auto-updated to this morning - I'm not sure

**Comment by ermiyaeskandary** [comment]
Just doublechecked - you don't have the latest version. 
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

> What version of the bot you are using. (Can be found at the top of the bot's code in Tamper/Greasemonkey.)

**Comment by stere0123** [comment]
Forced a script update and issue is resolved. oops
