### ISSUE TITLE
Bot does not avoid enemies good enough when boosting

### ISSUE THREAD

**Issue by ghost** [ermiyaeskandary/Slither.io-bot#58]
need more careful enemy avoidance while it is boosting after pray

**Comment by K00sKlust** [comment]
We can increase the collision radius multiplier while boosting.. Could that help?

**Comment by ghost** [comment]
maybe.. any other ideas?

**Comment by chancity** [comment]
@K00sKlust, I did that within the code and its effects weren't very beneficial....mainly because prey.

**Comment by ermiyaeskandary** [comment]
Could have guessed this would be an issue..

**Comment by Drflash55** [comment]
This would probably take a bit longer to code in, but the bot should be aware that if a prey is on the other side of a snake, it should ignore it entirely, and it also shouldn't go after it if it's incredibly close to a snake so it doesn't kamikaze itself.

**Comment by ghost** [comment]
@Drflash55 pray and also food
