### ISSUE TITLE
Bot goes just straight.

### ISSUE THREAD

**Issue by Ciao121** [ermiyaeskandary/Slither.io-bot#6]
It's only my problem?

**Comment by Ciao121** [comment]
Was my problem...

**Comment by Evanito** [comment]
It does seem to go straight sometimes.
1)Check if the bot is running by opening console (f12)   and looking for the log that says "Started."
2)If you can't find it, click back on the game and hit "t" on your keyboard
3)Sometimes the bot just goes straight while looking for food, give it a bit.

P.S. this project is only a couple days old, we are still working on many parts of the code and in its current state, the bot is only useful to watch amusedly as it spins in circles trying to eat food, then dies.

**Comment by Drflash55** [comment]
@FliiFe explains in detail as to why the bot goes straight at times...

https://slitheriobot.slack.com/archives/bugs/p1461694274000047

> I have figured out that the `mapToMouse` function doesn't work properly.
> `mapToMouse(snake.xx, snake.yy)` gives wrong results (should return `[0, 0]`)
> And `mapToMouse(px, py)` returns `[0, 0]`, exept `px` and `py` are not map coordinates
