### ISSUE TITLE
Change prey hunting range

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#60]
Okay, so at a certain range, the snake will lose more than it gains when hunting down prey.
- [ ] Find the length lost per distance when boosting
- [ ] Use that measure to see if it is worth it to go after it.

You know, instead of just trying to sprint across the map.

**Comment by haylinmoore** [comment]
It uses 2.4 per seconds.

**Comment by ermiyaeskandary** [comment]
We already have code to do that - we go after food relative to snake length

**Comment by ermiyaeskandary** [comment]
@FliiFe changed the code so we go after prey relative to our length

```
if (window.currentPrey.distance <= Math.pow(window.getSnakeLength(), 2) / 2) {
```

**Comment by Evanito** [comment]
But relative to length doesn't mean worth the lost length

**Comment by ermiyaeskandary** [comment]
But if it is based on length, then it wouldn't go too far if you are too small so it wouldn't lose more than it  gains.

**Comment by ermiyaeskandary** [comment]
Not applicable since it has been removed since version 0.9.0 https://github.com/ErmiyaEskandary/Slither.io-bot/issues/147
