### ISSUE TITLE
Collision radius issue

### ISSUE THREAD

**Issue by tjorim** [ermiyaeskandary/Slither.io-bot#61]
It looks like zooming out in the game (with the bot and collision detection enabled),
increases the radius of detection. I'm not sure if this behaviour is intended.

Below are two screenshots of the problem, the first one at the standard zoom level.
Sorry for the bad quality, if necessary I can provide better ones tomorrow.
![standard zoom](https://cloud.githubusercontent.com/assets/1294876/15032287/8d525968-125f-11e6-8a8e-6fd7d2f612f4.png)
![zoomed out](https://cloud.githubusercontent.com/assets/1294876/15032286/8d5246ee-125f-11e6-993b-51448566c31e.png)

**Comment by haylinmoore** [comment]
Hmm I have been having that same issue

**Comment by chancity** [comment]
I found the issue, itll be fixed soon
