### ISSUE TITLE
Bot randomly respawns

### ISSUE THREAD

**Issue by Evanito** [ermiyaeskandary/Slither.io-bot#62]
I have noticed that the bot will occasionally just start over. No death, no main menu screen, it just restarts.

**Comment by haylinmoore** [comment]
I have seen that happen too

**Comment by ghost** [comment]
i can confirm this

**Comment by dracco1993** [comment]
```
WebSocket is already in CLOSING or CLOSED state.oef @ game88mpi.js:100
Stopping Bot.
```

I just had the bot restart like this, checked the console, and I saw this.  Maybe it's related?

**Comment by ermiyaeskandary** [comment]
I think it's due to autorespawn setting. Can you toggle it and see if it makes a difference ? @Evanito

**Comment by ermiyaeskandary** [comment]
> state.oef

Your window.oef modification @K00sKlust ?

**Comment by tjbcg** [comment]
> `WebSocket is already in CLOSING or CLOSED state.oef`

This is a network issue (short connection lost). The slither's code set `playing` to false after encountering this, because it thinks the game has finished (even tho it has not). Thus the bot executes

``` javascript
} else {
        if (window.ranOnce) {
            //window.startInterval = setInterval(window.startBot, 1000);
            window.stopBot();
        }
    }
```

**Comment by Seple** [comment]
Bot randomly respawns #62 - and - Won't Start #63

The problem (and "Lag FPS") 
of the server high ping - another server low ping is not problem

I hope I'm not imposing???

**Comment by ermiyaeskandary** [comment]
> WebSocket is already in CLOSING or CLOSED state.oef
> This is a network issue (short connection lost). The slither's code set playing to false after encountering this, because it thinks the game has finished (even tho it has not). Thus the bot executes
> 
> } else {
>         if (window.ranOnce) {
>             //window.startInterval = setInterval(window.startBot, 1000);
>             window.stopBot();
>         }
>     }

So not the bot's problem I guess ?

**Comment by ermiyaeskandary** [comment]
I have never encountered this.

**Comment by ermiyaeskandary** [comment]
@Evanito So can you confirm it is due to slow internet connection as @FliiFe said ?

**Comment by dracco1993** [comment]
@ErmiyaEskandary Mine restarted when I was having internet issues.

I think if we add a check to see if we're stopped for several seconds in a row before restarting, that would fix this.

**Comment by Seple** [comment]
maybe detection ping and autoconect server low ping?

**Comment by Evanito** [comment]
@ErmiyaEskandary It is probably the result of loss on my wireless connection

**Comment by ermiyaeskandary** [comment]
Doesn't occur anymore. If it does, feel free to reopen
