### ISSUE TITLE
Won't Start

### ISSUE THREAD

**Issue by haylinmoore** [ermiyaeskandary/Slither.io-bot#63]
So I will have the user script install and go to slither.io and the bot won't start. Some times it can 5 - 6 reloads for the bot to start
INFO
Chrome
0.6.0
I have no idea what caused it

**Comment by ermiyaeskandary** [comment]
Please read this and then edit your issue :
https://github.com/ErmiyaEskandary/Slither.io-bot/wiki/Bug-reporting

**Comment by ermiyaeskandary** [comment]
I have no issues - can someone confirm this ? @Evanito @chancity @FliiFe @Drflash55 @K00sKlust

**Comment by tjbcg** [comment]
@ErmiyaEskandary Never experienced this issue. Works like a charm for me

**Comment by haylinmoore** [comment]
Updated

**Comment by kmatheussen** [comment]
Same problem. Yesterday I had lots of fun improving chancity's collision detection PR, but today I can't get the script to run.

I appended

```
console.log(" STARTING");
```

to the script, but nothing is printed to the console when reloading slither.io.

**Comment by kmatheussen** [comment]
I've tried uninstall / install from upstream, doesn't help.

**Comment by tjbcg** [comment]
Dumb question, but are you sure Tampermonkey/Greasemonkey is enabled ?

**Comment by kmatheussen** [comment]
google-chrome-stable-49.0.2623.112-1.x86_64 / tampermonkey.
Yes, it's enabled. Disabled/enabled/uninstall/install, tried lots of things.

**Comment by kmatheussen** [comment]
google-chrome-stable-49.0.2623.112-1.x86_64 / tampermonkey.
Yes, it's enabled. Disabled/enabled/uninstall/install, tried lots of things.

**Comment by kmatheussen** [comment]
Fixed it by reinstalling tampermonkey.

**Comment by tjbcg** [comment]
Oh, and BTW, chrome 50 has been released :-)

**Comment by ermiyaeskandary** [comment]
Has never occurred for me. Works like a charm. Maybe try reinstalling tampermonkey/greasemonkey or your browser ? Reinstall the script ? Clear the cache ?
