### ISSUE TITLE
Gitter

### ISSUE THREAD

**Issue by haylinmoore** [ermiyaeskandary/Slither.io-bot#64]
I think we should use gitter so that anyone can join and voice what they think about the bot and also we will not have the invite issues of slack

**Comment by chancity** [comment]
EDIT BY @ERMIYAESKANDARY : removed until further notice

**Comment by ermiyaeskandary** [comment]
https://gitter.im/ErmiyaEskandary/Slither.io-bot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
