### ISSUE TITLE
Important lags since #56 on low-end devices

### ISSUE THREAD

**Issue by tjbcg** [ermiyaeskandary/Slither.io-bot#68]
#56 Introduced huge lags. It needs fixing ASAP

**Comment by tjbcg** [comment]
Oh, forgot to say that was only on low-end devices

**Comment by ermiyaeskandary** [comment]
low end _devices_ ?

**Comment by ermiyaeskandary** [comment]
Obviously, #56 will increase CPU usage - it's enemy avoidance.

**Comment by ErmiyaEskandary** [comment]
I was thinking we could have a separate branch for enemy avoidance until it doesn't cause lag and all the "issues" are fixed

**Comment by ermiyaeskandary** [comment]
Have you tried mobile rendering on that low end device ?

**Comment by dracco1993** [comment]
By "low-end devices" are we talking phones, or laptops, or what?

**Comment by Drflash55** [comment]
"Low-end devices" means the computers and laptops that were made back in 2006 - 2009. They don't have the kind of graphics card or processor to handle the games of today...

**Comment by ermiyaeskandary** [comment]
When you say devices, I thought of phones as well @dracco1993

**Comment by dracco1993** [comment]
@Drflash55 That was not meant to be a jab at anyone, I was simply trying to figure out where this was happening.

**Comment by ermiyaeskandary** [comment]
Lag fixed ?

**Comment by ermiyaeskandary** [comment]
Lag fixed ?
