### ISSUE TITLE
[Suggestion] Manual respawn and manual death

### ISSUE THREAD

**Issue by Drflash55** [ermiyaeskandary/Slither.io-bot#70]
This can seem redundant, but it has it's uses...

Manual respawn can be implemented so you can jump from one part of the map to the other. It makes it easier to get around faster.

Manual death makes it so that you can access the main menu faster without refreshing your game.

Give your thoughts on whether this would be a useful feature to implement over time...

**Comment by Seple** [comment]
I'm yes + please nonstadard skins :)

I hope I'm not imposing???

**Comment by haylinmoore** [comment]
yes this would be good!

**Comment by ermiyaeskandary** [comment]
Great - I'll do it right now. What button for quitting to the main menu ?

**Comment by ermiyaeskandary** [comment]
@Seple Make a new issue for nonstandard skins.

**Comment by Seple** [comment]
[ESC] Respawn + [Q] Die ? = full package

**Comment by ermiyaeskandary** [comment]
Can you check the latest version to see if it works ? I can't check right now.

**Comment by ermiyaeskandary** [comment]
@Seple Join our Gitter by the way - you can login using your Github credentials.

**Comment by Seple** [comment]
> @Seple Dołącz do naszej gitter przy okazji - możesz zalogować się przy użyciu poświadczeń GitHub

thank you No impose oneself on somebody

**Comment by ermiyaeskandary** [comment]
> thank you NO impose oneself on somebody
> ??

**Comment by Seple** [comment]
"Impose oneself on somebody"
I do not want to be rude.
Also my language english is not good.

**Comment by ermiyaeskandary** [comment]
Impose
force (an unwelcome decision or ruling) on someone.

I wasn't forcing you - you don't need to join Gitter but it was you that said :

> I would really like to communicate with you guys on slack or skype...something.

**something** - Gitter 

> Not really an issue but I have no way of communicating so

**Comment by ermiyaeskandary** [comment]
nvm...

**Comment by Seple** [comment]
Is it possible to hack the game: "Bigbangempire" made ​​by you? 
because it does not exist

**Comment by ErmiyaEskandary** [comment]
Why did I search that ? Should have guessed...
But honestly, no. Sorry...

**Comment by ermiyaeskandary** [comment]
Manual death implemented - Q

**Comment by ermiyaeskandary** [comment]
Manual respawn being working on
