### ISSUE TITLE
auto skin rotator - manual skin changer 

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#71]
Please developer add on non standard skins 

[W] Toggle Skin Rotator (funny disco)+ [X] Change Skin (manually) = full package

Who agrees ? Thumbs up or thumbs down

**Comment by ermiyaeskandary** [comment]
Do we currently have 27 skins ?

**Comment by Seple** [comment]
Stadard + no stadard = 54 skins

Thank you :)

**Comment by ermiyaeskandary** [comment]
What do you mean by no standard ?

**Comment by Seple** [comment]
Stadard game clear no script (http://slither.io/ ---->>> click "change skin" = 30 skins)

Here https://greasyfork.org/pl/scripts/19416-slither-io-slithere-com-v3-0 stanadard and no stadard = 54 skins

**Comment by ermiyaeskandary** [comment]
Obfuscated - in the normal game we have 27... Don't we ?

**Comment by Seple** [comment]
All the site http://slither.io/ 29 or 30 skins

**Comment by ermiyaeskandary** [comment]
@Seple Yeah - 30 my mistake...

**Comment by ermiyaeskandary** [comment]
Done with latest commit coming up in a min...
