### ISSUE TITLE
Bot does not avoid world border

### ISSUE THREAD

**Issue by tom-n96** [ermiyaeskandary/Slither.io-bot#72]
If the bot strays too far from the food while on the edge of the map, it seems to go in a straight line directly to the world border where it dies.

**Comment by dracco1993** [comment]
This may not be an issue.  Last night mine was avoiding it correctly, so I'd like to make sure to test this with the most recent version before working on a fix.

**Comment by ermiyaeskandary** [comment]
@phatass69 This could be two separate issues. The title is a different issue from the description. The snake doesn't avoid world border - issue 1 - but _apparently_ it goes towards the world border - issue 2 . @dracco1993

**Comment by tom-n96** [comment]
@ErmiyaEskandary It doesn't specifically aim towards the border, but if there is no food or other snakes it will go in a straight line until it hits the border. I could have worded that more clearly I suppose.

**Comment by ermiyaeskandary** [comment]
@OneEyed possible with latest grid method ?

**Comment by ermiyaeskandary** [comment]
Avoids the wall border now...
