### ISSUE TITLE
Bot doesn't prioritize collision detection based on distance 

### ISSUE THREAD

**Issue by tom-n96** [ermiyaeskandary/Slither.io-bot#73]
I've noticed that when using a higher collision radius multiplier, the bot will not prioritize threats based on distance, but rather what threat is detected first. It will turn and avoid any threat until it is out of range, even if that means running into another snake in the process.

**Comment by ermiyaeskandary** [comment]
It prioritises threats based on the closest one **within** the radiuss

**Comment by tom-n96** [comment]
@ErmiyaEskandary, it seems as though it determines something to be a threat and then doesn't update the collision detection until after the other threat is out of range. Almost every time i've run the bot it dies while in the process of avoiding another threat. If there happens to be something else in the way, it will just run straight into it, without making any attempt to avoid it or giving any sign that it even recognizes there is another snake directly in front of it. I'll try and get a video of the issue I'm talking about.

**Comment by ermiyaeskandary** [comment]
> I'll try and get a video of the issue I'm talking about.

:+1:

**Comment by tom-n96** [comment]
@ErmiyaEskandary [Video is here](https://www.youtube.com/watch?v=-c2VScGw-WU)

You can see 0:07 seconds in it turns to avoid a snake and then at around 0:12 it hits another snake which it makes no attempt to avoid until the other snake goes out of range, which at that point was too late. There are a couple more examples in there as well.

This is the most recent version of the script, though the issue seems to have been in there since the collision detection was first implemented. You can see it significantly affects the functionality of the bot when using higher radius multipliers.  

I'll try to take a look at the code later and see if I can help out, but I need to finish a java project for my final exam.

**Comment by ermiyaeskandary** [comment]
I think this is due to the radius being too big and hence it cannot account for multiple snaked within the radius. This is natural as this is a new feature and will _surely_ be improved in the future.

**Comment by kmatheussen** [comment]
Fixed here:
https://github.com/ErmiyaEskandary/Slither.io-bot/pull/79/commits/320e174dcfdc2ed42bf1b621a03990a43e76334b
