### ISSUE TITLE
Defense mode - Bot toggle

### ISSUE THREAD

**Issue by ermiyaeskandary** [ermiyaeskandary/Slither.io-bot#74]
When the bot is toggled off while defense is toggled on, the bot stays in defense mode and "jitters" around when you try to move it.

**Comment by dracco1993** [comment]
The solution is simple.  When the bot is turned off:
- Set acceleration to 0
- Move the mouse to the center of the screen
- Set both left and right arrow keys to false

**Comment by ermiyaeskandary** [comment]
You implemented it - do you want to fix it ? ;)

**Comment by ermiyaeskandary** [comment]
I make issues for issues - I never said it was hard :) I make them for reference and history

**Comment by ChadSki** [comment]
Wasn't this fixed?

**Comment by ermiyaeskandary** [comment]
@ChadSki I still see it occurring.

**Comment by ermiyaeskandary** [comment]
Not applicable since version 0.9.0 
https://github.com/ErmiyaEskandary/Slither.io-bot/issues/146
