### ISSUE TITLE
[Suggestion] Graphic Option

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#75]
Solution Lags FPS with --->  https://greasyfork.org/pl/scripts/19416-slither-io-slithere-com-v3-0

> Option Graphic Quality : Optimizer

You can add to Slither.io-bot?
then with just one Hack

**Comment by ermiyaeskandary** [comment]
Wouldn't be useful - #40

**Comment by Seple** [comment]
OK Sorry
