### ISSUE TITLE
Suggestion: Put all bot variables into a new object, to avoid future name collision

### ISSUE THREAD

**Issue by kmatheussen** [ermiyaeskandary/Slither.io-bot#82]
E.g instead of window.getDistanceFromMe, use window.bot.getDistanceFromMe.
This also makes the code clearer, separating bot names from slither.io names.

**Comment by ermiyaeskandary** [comment]
We could do this possibly but if we have too many functions, then typing .bot wastes time. Maybe we could have a commented out "table" which specifies which functions are for the bot and maybe a description ?
Add your reaction..

**Comment by tjbcg** [comment]
> to avoid future name collision

What do you mean exactly ?

**Comment by dracco1993** [comment]
He's saying that'll make it easier to, at a glance, know which methods/variables are implemented by out bot, versus things that are actual slither.io methods/variables.

I agree with this thinking, although I'd say that it's generally just a programmer-preference kinda thing.

**Comment by ChadSki** [comment]
Here's my stab at organizing things, what do you think? It covers most functions but I didn't sort everything -- sort of a rough draft.

Edit: see referenced pull request.

**Comment by ermiyaeskandary** [comment]
Done.
