### ISSUE TITLE
Longest length today text covers script's text

### ISSUE THREAD

**Issue by kakol20** [ermiyaeskandary/Slither.io-bot#83]
http://img.prntscr.com/img?url=http://i.imgur.com/rPgBWeP.png

**Comment by tjbcg** [comment]
Confirmed

**Comment by tjbcg** [comment]
Could we just disable the longest length today message ?

**Comment by Drflash55** [comment]
@FliiFe You can do this three ways.
1. Disable the longest length message.
2. Move the longest length message.
3. Move the bot HUD display so it's not overlapping the longest length message.

**Comment by ermiyaeskandary** [comment]
What if we become the longest snake ? Option 2 and 3 are on the table - if we can move it, than option 2. If we can't option 3.

**Comment by Seple** [comment]
hmmm
3 - Change location HUD - to the radar?
4- Change location HUD - bottom in line?

**Comment by ChadSki** [comment]
Why not just slide the menu options down a bit?
