### ISSUE TITLE
[Suggestion] Add toggle to boost for food clusters

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#87]
It is really good that you can add it as another option ?
#86

**Comment by ermiyaeskandary** [comment]
Testing two PRs...

**Comment by Seple** [comment]
Proszę opcje szybkości jedzenia - klucz umożliwić

**Comment by ermiyaeskandary** [comment]
??

**Comment by Seple** [comment]
work on key - menu option

**Comment by ermiyaeskandary** [comment]
Oh - you meant a option you can toggle. Sorry - I misunderstood the issue

**Comment by Seple** [comment]
> Oh - you meant a option you can toggle. Sorry - I misunderstood the issue

Yes. 
I'm sorry for my language english is not good.

**Comment by Seple** [comment]
and new problem correct improvement detect (speed food) colision

**Comment by Seple** [comment]
Can add auto Option: "decrease collision radius multiplier" in mode "Speed food" ? 
- Closer to the body to other snakes to when to eat  - Closer to the body while eating

**Comment by ermiyaeskandary** [comment]
Make an issue - these are good ideas but we need separate issues so we can track them.

**Comment by Seple** [comment]
Please this is the topic, Labels : Problem

I 'm sorry for my language Angielski is not good. I have difficulty in writing with understanding. :(

**Comment by Seple** [comment]
OK ;)

**Comment by ermiyaeskandary** [comment]
Do we actually need toggles for everything ? The screen is getting cluttered...

**Comment by Seple** [comment]
flexible ability to configure and after setting the hiding menu?

maybe a new place suitable for menu 
look ------>>> http://s32.postimg.org/4u4n85zid/menu.jpg

**Comment by ermiyaeskandary** [comment]
@Seple Not a bad idea at all...

**Comment by ermiyaeskandary** [comment]
TBH, I think we don't need toggles for everything - then it wouldn't be a bot. It would be a sort of human assistance mod, which isn't what this is. The bot should be able to decide on its own..
