### ISSUE TITLE
[Bug] disabling bot does not disable boost

### ISSUE THREAD

**Issue by tjorim** [ermiyaeskandary/Slither.io-bot#90]
Browser: Google Chrome v50
Bot version: 0.7.2

Problem:
Disabling the bot while it was boosting does not end the boost. You need to click and release your mouse button to stop the boost. Also the snake doesn't go to your current actual mouse coordinates but stays heading its current direction.

Solution:
When executing the stopBot()-function, update the mouse coordinates before handing the mouse listener back over and setAcceleration back to 0.

This would change the code on line 178 to:

``` javascript
// Stops the bot
window.stopBot = function() {
    window.log('Stopping Bot.');
    // Disable the "sprint"
    window.setAcceleration(0);
    // Update the coordinates to the current mouse location
    window.setMouseCoordinates(??, ??) // I don't know how to get the mouse coordinates, is this possible?
    // Re enable the original onmousemove function
    window.onmousemove = window.mousemovelistener;
    window.isBotRunning = false;
    // Clear the interval which starts the bot
};
```

**Comment by Seple** [comment]
Yes! ...with #54 - really fast (milliseconds) reaction :+1:

**Comment by ermiyaeskandary** [comment]
@FliiFe Would this work ?

**Comment by ermiyaeskandary** [comment]
@tjorim 

``` javascript
window.onmousemove = window.mousemovelistener;
```

This already sets the mouse coordinates to where out mouse is. Can't we just do:

``` javascript
 window.setAcceleration(0);
```

when the bot is stopping ?

**Comment by tjorim** [comment]
@ErmiyaEskandary Yes, that would do it. Altough the slither doesn't move towards your mouse until you move it, it isn't as big a problem as the slither that keeps going full speed.

**Comment by ermiyaeskandary** [comment]
Well obviously you would move it :)
