### ISSUE TITLE
Bot is not aggressive enough about going after big piles of food

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#94]
Can add auto Option: "decrease collision radius multiplier" in mode "Speed food" dead snake?

Closer to the body to other snakes to when to eat dead snake - Closer to the body while eating dead snake 
(e.g. decrease distanse 60% the normal setting option -  "A / S - Collision radius multiplier increase / decrease" - when moments while eating dead snake)

**Comment by chancity** [comment]
Added this in this PR
https://github.com/ErmiyaEskandary/Slither.io-bot/pull/95

**Comment by Seple** [comment]
...and now they will be tested. Thank you for your work. ;)

**Comment by Seple** [comment]
It runs worse than it was. You do not understand me. Sorry

**Comment by chancity** [comment]
yeah the goodPath function is pretty CPU intensive

**Comment by Seple** [comment]
decrease distanse only this when the eating dead snake (Closer to the body while eating dead snake)

**Comment by chancity** [comment]
try it now

**Comment by Seple** [comment]
No No!

Please help @ksofiyuk

**Comment by chancity** [comment]
What is happening? it uses his algorithm still, it just checks to see if the path is being blocked by a collision part now.

**Comment by chancity** [comment]
record a video of it maybe?

**Comment by chancity** [comment]
whats your FPS?

**Comment by Seple** [comment]
Collisions are more frequent and not creeps to eat and snake body obstacles e.t.c

Play and check your version and the previous

**Comment by ChadSki** [comment]
I think Seple is asking for an override for collision avoidance when there is lots of food.

The bot is still too shy of other snakes while around big food, which it should be aggressively claiming.

If there is a massive pile of food, the bot should temporarily decrease its collision radius to the bare minimum needed to not crash, rather than a larger fearful radius.

**Comment by ChadSki** [comment]
Actually, I think increasing the collision radius while accelerating makes this problem worse. When the bot speeds up towards food, it becomes _more frightened_ of other snakes and wants to stay a larger distance away.

**Comment by Seple** [comment]
"Speed food" dead snake = decrease - option Collision radius multiplier decrease <--- for a while when moments while eating dead snake

Option: "A / S  Collision radius multiplier increase / decrease"
automatic temporarily reduce ( - 50% decrease) while eating a dead snake....

vivid description of http://postimg.org/image/5bvh6wn29/ 

when he eating dead snake closer other snake

**Comment by Seple** [comment]
#95 it works Idel. Now aggressively fighting for eating dead snake. Thank you. ;)

**Comment by Seple** [comment]
(will be held without) My mistake please close the topic and no problem. Sorry

**Comment by Seple** [comment]
Can't wait :+1:

**Comment by Seple** [comment]
I'm doing fine.

`var speedingMultiplier = (window.snake.sp > 10) ? 0.8 : 1.0;`

or max aggressive

`var speedingMultiplier = (window.snake.sp > 10) ? 0.7 : 1.0;`

is it good ?

Infect me and wants to know more about java ;)

**Comment by Seple** [comment]
Solution:

`var speedingMultiplier = (window.snake.sp > 10) ? 1.5 : 1.0;
     if (typeof window.currentFood  != 'undefined' && window.currentFood.clusterScore >= 70) {
    speedingMultiplier = 0.8;
}
`

**Comment by Seple** [comment]
the current code is sufficient to add: `var speedingMultiplier = (window.snake.sp> 10)? 1.0: 1.0`

**Comment by ermiyaeskandary** [comment]
@Seple Why not make a PR ?

**Comment by Seple** [comment]
I do not know how to program in Java :(

**Comment by ermiyaeskandary** [comment]
First, I need to do something else then I might do that.

**Comment by ermiyaeskandary** [comment]
Latest PR merge ?

**Comment by ermiyaeskandary** [comment]
Doesn't apply anymore.  Doesn't boost currently

**Comment by ChadSki** [comment]
The snake is still too scared of collisions to go after big food piles...

**Comment by Seple** [comment]
> If there is a massive pile of food, the bot should temporarily decrease its collision radius to the bare minimum needed to not crash, rather than a larger fearful radius.
> 
> The snake is still too scared of collisions to go after big food piles...

I agree

Zero not aggressively fighting for eating dead snake :(

**Comment by ermiyaeskandary** [comment]
Implemented
