### ISSUE TITLE
[Suggestion] Add toggle to boost when there is a dead snake

### ISSUE THREAD

**Issue by Seple** [ermiyaeskandary/Slither.io-bot#96]
Add menu on or off "Speed food" dead snake
Is it possible?

**Comment by ermiyaeskandary** [comment]
Do we actually need toggles for everything ? The screen is getting cluttered...

**Comment by Seple** [comment]
flexible ability to configure and after setting the hidden menu?

hmmm 

maybe a new place suitable for menu 
look ---> http://s32.postimg.org/4u4n85zid/menu.jpg

**Comment by ermiyaeskandary** [comment]
We can't have a toggle for everything - you have to deal with it :+1:  
We can't have toggles for every single thing - some are supposed to be inbuilt and not toggled and we have FPS decreases with every new toggle as we are adding to the event listener.
